////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD7C51G_H_
#define _MSD7C51G_H_

#define PAD_NC 9999
#define PAD_GND 0

#define PIN_95 PAD_IRIN
#define PAD_IRIN 1
#define GPIO_PAD_1 GPIO0
#ifndef PIN_95_IS_GPIO
#define PIN_95_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO PIN_95_IS_GPIO
#endif 

#define PIN_96 PAD_HDMI_CEC
#define PAD_HDMI_CEC 2
#define GPIO_PAD_2 GPIO1
#ifndef PIN_96_IS_GPIO
#define PIN_96_IS_GPIO 0
#endif 
#ifndef PAD_HDMI_CEC_IS_GPIO
#define PAD_HDMI_CEC_IS_GPIO PIN_96_IS_GPIO
#endif 

#define PIN_97 PAD_UART_RX
#define PAD_UART_RX 4
#define GPIO_PAD_4 GPIO3
#ifndef PIN_97_IS_GPIO
#define PIN_97_IS_GPIO 0
#endif 
#ifndef PAD_UART_RX_IS_GPIO
#define PAD_UART_RX_IS_GPIO PIN_97_IS_GPIO
#endif 

#define PIN_98 PAD_UART_TX
#define PAD_UART_TX 3
#define GPIO_PAD_3 GPIO2
#ifndef PIN_98_IS_GPIO
#define PIN_98_IS_GPIO 0
#endif 
#ifndef PAD_UART_TX_IS_GPIO
#define PAD_UART_TX_IS_GPIO PIN_98_IS_GPIO
#endif 

#define PIN_99 PAD_GPIO_PM5
#define PAD_GPIO_PM5 9
#define GPIO_PAD_9 GPIO8
#ifndef PIN_99_IS_GPIO
#define PIN_99_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO PIN_99_IS_GPIO
#endif 

#define PIN_100 PAD_GPIO_PM1
#define PAD_GPIO_PM1 5
#define GPIO_PAD_5 GPIO4
#ifndef PIN_100_IS_GPIO
#define PIN_100_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO PIN_100_IS_GPIO
#endif 

#define PIN_101 PAD_GPIO_PM2
#define PAD_GPIO_PM2 6
#define GPIO_PAD_6 GPIO5
#ifndef PIN_101_IS_GPIO
#define PIN_101_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO PIN_101_IS_GPIO
#endif 

#define PIN_102 PAD_GPIO_PM3
#define PAD_GPIO_PM3 7
#define GPIO_PAD_7 GPIO6
#ifndef PIN_102_IS_GPIO
#define PIN_102_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO PIN_102_IS_GPIO
#endif 

#define PIN_103 PAD_GPIO_PM6
#define PAD_GPIO_PM6 10
#define GPIO_PAD_10 GPIO9
#ifndef PIN_103_IS_GPIO
#define PIN_103_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO PIN_103_IS_GPIO
#endif 

#define PIN_104 PAD_GPIO_PM7
#define PAD_GPIO_PM7 11
#define GPIO_PAD_11 GPIO10
#ifndef PIN_104_IS_GPIO
#define PIN_104_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO PIN_104_IS_GPIO
#endif 

#define PIN_105 PAD_GPIO_PM8
#define PAD_GPIO_PM8 12
#define GPIO_PAD_12 GPIO11
#ifndef PIN_105_IS_GPIO
#define PIN_105_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO PIN_105_IS_GPIO
#endif 

#define PIN_108 PAD_GPIO_PM4
#define PAD_GPIO_PM4 8
#define GPIO_PAD_8 GPIO7
#ifndef PIN_108_IS_GPIO
#define PIN_108_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO PIN_108_IS_GPIO
#endif 

#define PIN_109 PAD_PWM0
#define PAD_PWM0 13
#define GPIO_PAD_13 GPIO12
#ifndef PIN_109_IS_GPIO
#define PIN_109_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO PIN_109_IS_GPIO
#endif 

#define PIN_110 PAD_PWM1
#define PAD_PWM1 14
#define GPIO_PAD_14 GPIO13
#ifndef PIN_110_IS_GPIO
#define PIN_110_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO PIN_110_IS_GPIO
#endif 

#define PIN_111 PAD_PWM2
#define PAD_PWM2 15
#define GPIO_PAD_15 GPIO14
#ifndef PIN_111_IS_GPIO
#define PIN_111_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO PIN_111_IS_GPIO
#endif 

#define PIN_112 PAD_SAR0
#define PAD_SAR0 16
#define GPIO_PAD_16 GPIO15
#ifndef PIN_112_IS_GPIO
#define PIN_112_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO PIN_112_IS_GPIO
#endif 

#define PIN_113 PAD_SAR1
#define PAD_SAR1 17
#define GPIO_PAD_17 GPIO16
#ifndef PIN_113_IS_GPIO
#define PIN_113_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO PIN_113_IS_GPIO
#endif 

#define PIN_114 PAD_SAR2
#define PAD_SAR2 18
#define GPIO_PAD_18 GPIO17
#ifndef PIN_114_IS_GPIO
#define PIN_114_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO PIN_114_IS_GPIO
#endif 

#define PIN_115 PAD_SAR3
#define PAD_SAR3 19
#define GPIO_PAD_19 GPIO18
#ifndef PIN_115_IS_GPIO
#define PIN_115_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO PIN_115_IS_GPIO
#endif 

#define PIN_120 PAD_NAND_RBZ
#define PAD_NAND_RBZ 47
#define GPIO_PAD_47 GPIO46
#ifndef PIN_120_IS_GPIO
#define PIN_120_IS_GPIO 0
#endif 
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO PIN_120_IS_GPIO
#endif 

#define PIN_121 PAD_NAND_REZ
#define PAD_NAND_REZ 46
#define GPIO_PAD_46 GPIO45
#ifndef PIN_121_IS_GPIO
#define PIN_121_IS_GPIO 0
#endif 
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO PIN_121_IS_GPIO
#endif 

#define PIN_122 PAD_NAND_CEZ
#define PAD_NAND_CEZ 45
#define GPIO_PAD_45 GPIO44
#ifndef PIN_122_IS_GPIO
#define PIN_122_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO PIN_122_IS_GPIO
#endif 

#define PAD_NAND_CEZ1 9999
#ifndef PAD_NAND_CEZ1_IS_GPIO
#define PAD_NAND_CEZ1_IS_GPIO 0
#endif 

#define PIN_123 PAD_NAND_CLE
#define PAD_NAND_CLE 43
#define GPIO_PAD_43 GPIO42
#ifndef PIN_123_IS_GPIO
#define PIN_123_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO PIN_123_IS_GPIO
#endif 

#define PIN_125 PAD_NAND_ALE
#define PAD_NAND_ALE 42
#define GPIO_PAD_42 GPIO41
#ifndef PIN_125_IS_GPIO
#define PIN_125_IS_GPIO 0
#endif 
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO PIN_125_IS_GPIO
#endif 

#define PIN_126 PAD_NAND_WEZ
#define PAD_NAND_WEZ 41
#define GPIO_PAD_41 GPIO40
#ifndef PIN_126_IS_GPIO
#define PIN_126_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO PIN_126_IS_GPIO
#endif 

#define PIN_127 PAD_NAND_WPZ
#define PAD_NAND_WPZ 40
#define GPIO_PAD_40 GPIO39
#ifndef PIN_127_IS_GPIO
#define PIN_127_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO PIN_127_IS_GPIO
#endif 

#define PIN_128 PAD_NAND_AD0
#define PAD_NAND_AD0 48
#define GPIO_PAD_48 GPIO47
#ifndef PIN_128_IS_GPIO
#define PIN_128_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD0_IS_GPIO
#define PAD_NAND_AD0_IS_GPIO PIN_128_IS_GPIO
#endif 

#define PIN_129 PAD_NAND_AD1
#define PAD_NAND_AD1 49
#define GPIO_PAD_49 GPIO48
#ifndef PIN_129_IS_GPIO
#define PIN_129_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD1_IS_GPIO
#define PAD_NAND_AD1_IS_GPIO PIN_129_IS_GPIO
#endif 

#define PIN_130 PAD_NAND_AD2
#define PAD_NAND_AD2 50
#define GPIO_PAD_50 GPIO49
#ifndef PIN_130_IS_GPIO
#define PIN_130_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD2_IS_GPIO
#define PAD_NAND_AD2_IS_GPIO PIN_130_IS_GPIO
#endif 

#define PIN_131 PAD_NAND_AD3
#define PAD_NAND_AD3 51
#define GPIO_PAD_51 GPIO50
#ifndef PIN_131_IS_GPIO
#define PIN_131_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD3_IS_GPIO
#define PAD_NAND_AD3_IS_GPIO PIN_131_IS_GPIO
#endif 

#define PIN_132 PAD_NAND_AD4
#define PAD_NAND_AD4 52
#define GPIO_PAD_52 GPIO51
#ifndef PIN_132_IS_GPIO
#define PIN_132_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD4_IS_GPIO
#define PAD_NAND_AD4_IS_GPIO PIN_132_IS_GPIO
#endif 

#define PIN_133 PAD_NAND_AD5
#define PAD_NAND_AD5 53
#define GPIO_PAD_53 GPIO52
#ifndef PIN_133_IS_GPIO
#define PIN_133_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD5_IS_GPIO
#define PAD_NAND_AD5_IS_GPIO PIN_133_IS_GPIO
#endif 

#define PIN_134 PAD_NAND_AD6
#define PAD_NAND_AD6 54
#define GPIO_PAD_54 GPIO53
#ifndef PIN_134_IS_GPIO
#define PIN_134_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD6_IS_GPIO
#define PAD_NAND_AD6_IS_GPIO PIN_134_IS_GPIO
#endif 

#define PIN_135 PAD_NAND_AD7
#define PAD_NAND_AD7 55
#define GPIO_PAD_55 GPIO54
#ifndef PIN_135_IS_GPIO
#define PIN_135_IS_GPIO 0
#endif 
#ifndef PAD_NAND_AD7_IS_GPIO
#define PAD_NAND_AD7_IS_GPIO PIN_135_IS_GPIO
#endif 

#define PIN_137 PAD_SM0_CD
#define PAD_SM0_CD 56
#define GPIO_PAD_56 GPIO55
#ifndef PIN_137_IS_GPIO
#define PIN_137_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CD_IS_GPIO
#define PAD_SM0_CD_IS_GPIO PIN_137_IS_GPIO
#endif 

#define PIN_138 PAD_SM0_RST
#define PAD_SM0_RST 57
#define GPIO_PAD_57 GPIO56
#ifndef PIN_138_IS_GPIO
#define PIN_138_IS_GPIO 0
#endif 
#ifndef PAD_SM0_RST_IS_GPIO
#define PAD_SM0_RST_IS_GPIO PIN_138_IS_GPIO
#endif 

#define PIN_139 PAD_SM0_VCC
#define PAD_SM0_VCC 58
#define GPIO_PAD_58 GPIO57
#ifndef PIN_139_IS_GPIO
#define PIN_139_IS_GPIO 0
#endif 
#ifndef PAD_SM0_VCC_IS_GPIO
#define PAD_SM0_VCC_IS_GPIO PIN_139_IS_GPIO
#endif 

#define PIN_141 PAD_SM0_IO
#define PAD_SM0_IO 59
#define GPIO_PAD_59 GPIO58
#ifndef PIN_141_IS_GPIO
#define PIN_141_IS_GPIO 0
#endif 
#ifndef PAD_SM0_IO_IS_GPIO
#define PAD_SM0_IO_IS_GPIO PIN_141_IS_GPIO
#endif 

#define PIN_142 PAD_SM0_CLK
#define PAD_SM0_CLK 60
#define GPIO_PAD_60 GPIO59
#ifndef PIN_142_IS_GPIO
#define PIN_142_IS_GPIO 0
#endif 
#ifndef PAD_SM0_CLK_IS_GPIO
#define PAD_SM0_CLK_IS_GPIO PIN_142_IS_GPIO
#endif 

#define PIN_143 PAD_I2CM0_SCL
#define PAD_I2CM0_SCL 31
#define GPIO_PAD_31 GPIO30
#ifndef PIN_143_IS_GPIO
#define PIN_143_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SCL_IS_GPIO
#define PAD_I2CM0_SCL_IS_GPIO PIN_143_IS_GPIO
#endif 

#define PIN_144 PAD_I2CM0_SDA
#define PAD_I2CM0_SDA 32
#define GPIO_PAD_32 GPIO31
#ifndef PIN_144_IS_GPIO
#define PIN_144_IS_GPIO 0
#endif 
#ifndef PAD_I2CM0_SDA_IS_GPIO
#define PAD_I2CM0_SDA_IS_GPIO PIN_144_IS_GPIO
#endif 

#define PIN_145 PAD_TS0_CLK
#define PAD_TS0_CLK 66
#define GPIO_PAD_66 GPIO65
#ifndef PIN_145_IS_GPIO
#define PIN_145_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO PIN_145_IS_GPIO
#endif 

#define PIN_146 PAD_TS0_VLD
#define PAD_TS0_VLD 67
#define GPIO_PAD_67 GPIO66
#ifndef PIN_146_IS_GPIO
#define PIN_146_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO PIN_146_IS_GPIO
#endif 

#define PIN_147 PAD_TS0_SYNC
#define PAD_TS0_SYNC 68
#define GPIO_PAD_68 GPIO67
#ifndef PIN_147_IS_GPIO
#define PIN_147_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO PIN_147_IS_GPIO
#endif 

#define PIN_148 PAD_TS0_D7
#define PAD_TS0_D7 69
#define GPIO_PAD_69 GPIO68
#ifndef PIN_148_IS_GPIO
#define PIN_148_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO PIN_148_IS_GPIO
#endif 

#define PIN_149 PAD_TS0_D6
#define PAD_TS0_D6 70
#define GPIO_PAD_70 GPIO69
#ifndef PIN_149_IS_GPIO
#define PIN_149_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO PIN_149_IS_GPIO
#endif 

#define PIN_150 PAD_TS0_D5
#define PAD_TS0_D5 71
#define GPIO_PAD_71 GPIO70
#ifndef PIN_150_IS_GPIO
#define PIN_150_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO PIN_150_IS_GPIO
#endif 

#define PIN_151 PAD_TS0_D4
#define PAD_TS0_D4 72
#define GPIO_PAD_72 GPIO71
#ifndef PIN_151_IS_GPIO
#define PIN_151_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO PIN_151_IS_GPIO
#endif 

#define PIN_152 PAD_TS0_D3
#define PAD_TS0_D3 73
#define GPIO_PAD_73 GPIO72
#ifndef PIN_152_IS_GPIO
#define PIN_152_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO PIN_152_IS_GPIO
#endif 

#define PIN_153 PAD_TS0_D2
#define PAD_TS0_D2 74
#define GPIO_PAD_74 GPIO73
#ifndef PIN_153_IS_GPIO
#define PIN_153_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO PIN_153_IS_GPIO
#endif 

#define PIN_154 PAD_TS0_D1
#define PAD_TS0_D1 75
#define GPIO_PAD_75 GPIO74
#ifndef PIN_154_IS_GPIO
#define PIN_154_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO PIN_154_IS_GPIO
#endif 

#define PIN_155 PAD_TS0_D0
#define PAD_TS0_D0 76
#define GPIO_PAD_76 GPIO75
#ifndef PIN_155_IS_GPIO
#define PIN_155_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO PIN_155_IS_GPIO
#endif 

#define PIN_176 PAD_LED0
#define PAD_LED0 38
#define GPIO_PAD_38 GPIO37
#ifndef PIN_176_IS_GPIO
#define PIN_176_IS_GPIO 0
#endif 
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO PIN_176_IS_GPIO
#endif 

#define PIN_177 PAD_LED1
#define PAD_LED1 39
#define GPIO_PAD_39 GPIO38
#ifndef PIN_177_IS_GPIO
#define PIN_177_IS_GPIO 0
#endif 
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO PIN_177_IS_GPIO
#endif 

#define PIN_178 PAD_SM0_SWITCH
#define PAD_SM0_SWITCH 61
#define GPIO_PAD_61 GPIO60
#ifndef PIN_178_IS_GPIO
#define PIN_178_IS_GPIO 0
#endif 
#ifndef PAD_SM0_SWITCH_IS_GPIO
#define PAD_SM0_SWITCH_IS_GPIO PIN_178_IS_GPIO
#endif 

#define PIN_179 PAD_SM0_C4
#define PAD_SM0_C4 62
#define GPIO_PAD_62 GPIO61
#ifndef PIN_179_IS_GPIO
#define PIN_179_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C4_IS_GPIO
#define PAD_SM0_C4_IS_GPIO PIN_179_IS_GPIO
#endif 

#define PIN_180 PAD_SM0_C8
#define PAD_SM0_C8 63
#define GPIO_PAD_63 GPIO62
#ifndef PIN_180_IS_GPIO
#define PIN_180_IS_GPIO 0
#endif 
#ifndef PAD_SM0_C8_IS_GPIO
#define PAD_SM0_C8_IS_GPIO PIN_180_IS_GPIO
#endif 

#define PIN_181 PAD_ET_MDIO
#define PAD_ET_MDIO 20
#define GPIO_PAD_20 GPIO19
#ifndef PIN_181_IS_GPIO
#define PIN_181_IS_GPIO 0
#endif 
#ifndef PAD_ET_MDIO_IS_GPIO
#define PAD_ET_MDIO_IS_GPIO PIN_181_IS_GPIO
#endif 

#define PIN_182 PAD_ET_MDC
#define PAD_ET_MDC 21
#define GPIO_PAD_21 GPIO20
#ifndef PIN_182_IS_GPIO
#define PIN_182_IS_GPIO 0
#endif 
#ifndef PAD_ET_MDC_IS_GPIO
#define PAD_ET_MDC_IS_GPIO PIN_182_IS_GPIO
#endif 

#define PIN_183 PAD_ET_COL
#define PAD_ET_COL 22
#define GPIO_PAD_22 GPIO21
#ifndef PIN_183_IS_GPIO
#define PIN_183_IS_GPIO 0
#endif 
#ifndef PAD_ET_COL_IS_GPIO
#define PAD_ET_COL_IS_GPIO PIN_183_IS_GPIO
#endif 

#define PIN_184 PAD_ET_RXD0
#define PAD_ET_RXD0 23
#define GPIO_PAD_23 GPIO22
#ifndef PIN_184_IS_GPIO
#define PIN_184_IS_GPIO 0
#endif 
#ifndef PAD_ET_RXD0_IS_GPIO
#define PAD_ET_RXD0_IS_GPIO PIN_184_IS_GPIO
#endif 

#define PIN_185 PAD_ET_RXD1
#define PAD_ET_RXD1 24
#define GPIO_PAD_24 GPIO23
#ifndef PIN_185_IS_GPIO
#define PIN_185_IS_GPIO 0
#endif 
#ifndef PAD_ET_RXD1_IS_GPIO
#define PAD_ET_RXD1_IS_GPIO PIN_185_IS_GPIO
#endif 

#define PIN_186 PAD_ET_TX_CLK
#define PAD_ET_TX_CLK 25
#define GPIO_PAD_25 GPIO24
#ifndef PIN_186_IS_GPIO
#define PIN_186_IS_GPIO 0
#endif 
#ifndef PAD_ET_TX_CLK_IS_GPIO
#define PAD_ET_TX_CLK_IS_GPIO PIN_186_IS_GPIO
#endif 

#define PIN_189 PAD_ET_TXD0
#define PAD_ET_TXD0 26
#define GPIO_PAD_26 GPIO25
#ifndef PIN_189_IS_GPIO
#define PIN_189_IS_GPIO 0
#endif 
#ifndef PAD_ET_TXD0_IS_GPIO
#define PAD_ET_TXD0_IS_GPIO PIN_189_IS_GPIO
#endif 

#define PIN_190 PAD_ET_TXD1
#define PAD_ET_TXD1 27
#define GPIO_PAD_27 GPIO26
#ifndef PIN_190_IS_GPIO
#define PIN_190_IS_GPIO 0
#endif 
#ifndef PAD_ET_TXD1_IS_GPIO
#define PAD_ET_TXD1_IS_GPIO PIN_190_IS_GPIO
#endif 

#define PIN_191 PAD_ET_TX_EN
#define PAD_ET_TX_EN 28
#define GPIO_PAD_28 GPIO27
#ifndef PIN_191_IS_GPIO
#define PIN_191_IS_GPIO 0
#endif 
#ifndef PAD_ET_TX_EN_IS_GPIO
#define PAD_ET_TX_EN_IS_GPIO PIN_191_IS_GPIO
#endif 

#define PIN_192 PAD_I2S_OUT_MUTE
#define PAD_I2S_OUT_MUTE 33
#define GPIO_PAD_33 GPIO32
#ifndef PIN_192_IS_GPIO
#define PIN_192_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MUTE_IS_GPIO
#define PAD_I2S_OUT_MUTE_IS_GPIO PIN_192_IS_GPIO
#endif 

#define PIN_193 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 34
#define GPIO_PAD_34 GPIO33
#ifndef PIN_193_IS_GPIO
#define PIN_193_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO PIN_193_IS_GPIO
#endif 

#define PIN_194 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 35
#define GPIO_PAD_35 GPIO34
#ifndef PIN_194_IS_GPIO
#define PIN_194_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO PIN_194_IS_GPIO
#endif 

#define PIN_195 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 36
#define GPIO_PAD_36 GPIO35
#ifndef PIN_195_IS_GPIO
#define PIN_195_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO PIN_195_IS_GPIO
#endif 

#define PIN_196 PAD_I2S_OUT_SD0
#define PAD_I2S_OUT_SD0 37
#define GPIO_PAD_37 GPIO36
#ifndef PIN_196_IS_GPIO
#define PIN_196_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD0_IS_GPIO
#define PAD_I2S_OUT_SD0_IS_GPIO PIN_196_IS_GPIO
#endif 

#define PIN_197 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 64
#define GPIO_PAD_64 GPIO63
#ifndef PIN_197_IS_GPIO
#define PIN_197_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO PIN_197_IS_GPIO
#endif 

#define PIN_198 PAD_SPDIF_IN
#define PAD_SPDIF_IN 65
#define GPIO_PAD_65 GPIO64
#ifndef PIN_198_IS_GPIO
#define PIN_198_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO PIN_198_IS_GPIO
#endif 

#define PIN_199 PAD_GPIO
#define PAD_GPIO 29
#define GPIO_PAD_29 GPIO28
#ifndef PIN_199_IS_GPIO
#define PIN_199_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_IS_GPIO
#define PAD_GPIO_IS_GPIO PIN_199_IS_GPIO
#endif 

#define PIN_200 PAD_HDMI_HPD
#define PAD_HDMI_HPD 30
#define GPIO_PAD_30 GPIO29
#ifndef PIN_200_IS_GPIO
#define PIN_200_IS_GPIO 0
#endif 
#ifndef PAD_HDMI_HPD_IS_GPIO
#define PAD_HDMI_HPD_IS_GPIO PIN_200_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            0 
#define CHIP_HAS_I2S_OUT           0
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         0
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_KENYA

#endif /* _MSD7C51G_H_*/
