obj-$(CONFIG_MTD_UBI_ENHANCE_INIT) += ubi_en_init.o
obj-$(CONFIG_MTD_UBI_MLC) += ubi_mlc.o

EXTRA_CFLAGS += -I$(srctree)/drivers/mstar/unfd/inc/api/
EXTRA_CFLAGS += -I$(srctree)/drivers/mstar/unfd/inc/common
EXTRA_CFLAGS += -I$(srctree)/drivers/mstar/unfd/inc/config/
