# Copyright (c) 2008-2009 MStar Semiconductor, Inc.
# All rights reserved.
#
# AWK script to automatically generate uboot config file for board options

$2 == "ENABLE_MSTAR_TITANIA" {print "#define ENABLE_TITANIA " $3}
$2 == "ENABLE_MSTAR_TITANIA2" {print "#define ENABLE_TITANIA2 " $3}
$2 == "ENABLE_MSTAR_TITANIA3" {print "#define ENABLE_TITANIA3 " $3}
$2 == "ENABLE_MSTAR_TITANIA4" {print "#define ENABLE_TITANIA4 " $3}
$2 == "ENABLE_MSTAR_TITANIA7" {print "#define ENABLE_TITANIA7 " $3}
$2 == "ENABLE_MSTAR_TITANIA9" {print "#define ENABLE_TITANIA9 " $3}
$2 == "ENABLE_MSTAR_TITANIA13" {print "#define ENABLE_TITANIA13 " $3}
$2 == "ENABLE_MSTAR_AMBER1" {print "#define ENABLE_AMBER1 " $3}
$2 == "ENABLE_MSTAR_AMBER2" {print "#define ENABLE_AMBER2 " $3}
$2 == "ENABLE_MSTAR_AMBER3" {print "#define ENABLE_AMBER3 " $3}
$2 == "ENABLE_MSTAR_AMBER5" {print "#define ENABLE_AMBER5 " $3}
$2 == "ENABLE_MSTAR_AMBER6" {print "#define ENABLE_AMBER6 " $3}
$2 == "ENABLE_MSTAR_AMBER7" {print "#define ENABLE_AMBER7 " $3}
$2 == "ENABLE_MSTAR_AMETHYST" {print "#define ENABLE_AMETHYST " $3}
$2 == "ENABLE_MSTAR_KAISERIN" {print "#define ENABLE_KAISERIN " $3}
$2 == "ENABLE_MSTAR_EAGLE" {print "#define ENABLE_EAGLE " $3}
$2 == "ENABLE_MSTAR_EIFFEL" {print "#define ENABLE_EIFFEL " $3}
$2 == "ENABLE_MSTAR_NIKE" {print "#define ENABLE_NIKE " $3}
$2 == "ENABLE_MSTAR_MADISON" {print "#define ENABLE_MADISON " $3}
$2 == "ENABLE_MSTAR_MONET" {print "#define ENABLE_MONET " $3}
$2 == "ENABLE_MSTAR_CLIPPERS" {print "#define ENABLE_CLIPPERS " $3}
$2 == "ENABLE_MSTAR_MIAMI" {print "#define ENABLE_MIAMI " $3}
$2 == "ENABLE_MSTAR_MONACO" {print "#define ENABLE_MONACO " $3}
$2 == "ENABLE_MSTAR_MUJI" {print "#define ENABLE_MUJI " $3}
$2 == "ENABLE_MSTAR_CELTICS" {print "#define ENABLE_CELTICS " $3}
$2 == "ENABLE_MSTAR_NADAL" {print "#define ENABLE_NADAL " $3}
$2 == "ENABLE_MSTAR_EMERALD" {print "#define ENABLE_EMERALD " $3}
$2 == "ENABLE_MSTAR_NUGGET" {print "#define ENABLE_NUGGET " $3}
$2 == "ENABLE_MSTAR_NIKON" {print "#define ENABLE_NIKON " $3}
$2 == "ENABLE_MSTAR_MILAN" {print "#define ENABLE_MILAN " $3}
$2 == "ENABLE_MSTAR_EDISON" {print "#define ENABLE_EDISON " $3}
$2 == "ENABLE_MSTAR_AGATE" {print "#define ENABLE_AGATE " $3}
$2 == "ENABLE_MSTAR_EINSTEIN" {print "#define ENABLE_EINSTEIN " $3}
$2 == "ENABLE_MSTAR_EINSTEIN3" {print "#define ENABLE_EINSTEIN3 " $3}
$2 == "ENABLE_MSTAR_NAPOLI" {print "#define ENABLE_NAPOLI " $3}
$2 == "ENABLE_MSTAR_KRONUS" {print "#define ENABLE_KRONUS " $3}
$2 == "ENABLE_MSTAR_KENYA" {print "#define ENABLE_KENYA " $3}
$2 == "ENABLE_MSTAR_EUCLID" {print "#define ENABLE_EUCLID " $3}
$2 == "ENABLE_MSTAR_JANUS" {print "#define ENABLE_JANUS " $3}
$2 == "ENABLE_MSTAR_KAISER" {print "#define ENABLE_KAISER " $3}
$2 == "ENABLE_MSTAR_KRITI" {print "#define ENABLE_KRITI " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_FPGA" {print "#define ENABLE_BD_FPGA " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST055A_D01A_S" {print "#define ENABLE_BD_MST055A_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST055B_D01A_S" {print "#define ENABLE_BD_MST055B_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST055C_D01A_S" {print "#define ENABLE_BD_MST055C_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST055E_D01A_S" {print "#define ENABLE_BD_MST055E_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST064C_D01A_S" {print "#define ENABLE_BD_MST064C_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST064D_D01A_S" {print "#define ENABLE_BD_MST064D_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST064E_D01A_S" {print "#define ENABLE_BD_MST064E_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST072C_D01A" {print "#define ENABLE_BD_MST072C_D01A " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST072D_D01A_S" {print "#define ENABLE_BD_MST072D_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST072F_D01A_S" {print "#define ENABLE_BD_MST072F_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST072D_SKYWORTH" {print "#define ENABLE_BD_MST072D_SKYWORTH " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087B_S7_D01A_S" {print "#define ENABLE_BD_MST087B_S7_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087B_S7M_D01A_S" {print "#define ENABLE_BD_MST087B_S7M_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087C_D01A_S" {print "#define ENABLE_BD_MST087C_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087C_D02A_S" {print "#define ENABLE_BD_MST087C_D02A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087E_D01A" {print "#define ENABLE_BD_MST087E_D01A " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087E_D01A_S" {print "#define ENABLE_BD_MST087E_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087F_D01A" {print "#define ENABLE_BD_MST087F_D01A " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST087F_D01A_HX" {print "#define ENABLE_BD_MST087F_D01A_HX " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST536P_T3_10A" {print "#define ENABLE_BD_MST536P_T3_10A " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_GP2_DEMO1" {print "#define ENABLE_BD_GP2_DEMO1 " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST090A_D01A_S" {print "#define ENABLE_BD_MST090A_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST090B_D01A_S" {print "#define ENABLE_BD_MST090B_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST090C_D01A_S" {print "#define ENABLE_BD_MST090C_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST091A_D01A_S" {print "#define ENABLE_BD_MST091A_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST091B_D01A_S" {print "#define ENABLE_BD_MST091B_D01A_S " $3}
$2 == "ENABLE_MSTAR_JANUS_BD_MST092A_D01A_S" {print "#define ENABLE_BD_MST092A_D01A_S " $3}
$2 == "ENABLE_MSTAR_JANUS_BD_MST092B_D01A_S" {print "#define ENABLE_BD_MST092B_D01A_S " $3}
$2 == "ENABLE_MSTAR_JANUS_BD_MST092C_D01A_S" {print "#define ENABLE_BD_MST092C_D01A_S " $3}
$2 == "ENABLE_MSTAR_JANUS_BD_MST216A_JNS_10A_9463" {print "#define ENABLE_BD_MST216A_JNS_10A_9463 " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST106A_D01A_S" {print "#define ENABLE_BD_MST106A_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST106B_D01A_S" {print "#define ENABLE_BD_MST106B_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST110A_D01A_S" {print "#define ENABLE_BD_MST110A_D01A_S " $3}
$2 == "ENABLE_MSTAR_CONFIG_MSTAR_BD_JANUS2_FPGA" {print "#define ENABLE_BD_JANUS2_FPGA " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST110B_D01A_S" {print "#define ENABLE_BD_MST110B_D01A_S " $3}
$2 == "ENABLE_MSTAR_TITANIA_BD_MST119C_D01A_S" {print "#define ENABLE_BD_MST119C_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST131A_D01A_S" {print "#define ENABLE_BD_MST131A_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST131B_D01A_S" {print "#define ENABLE_BD_MST131B_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST132A_D01A_S_A7" {print "#define ENABLE_BD_MST132A_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST132B_D01A_S" {print "#define ENABLE_BD_MST132B_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST132C_D01A_S" {print "#define ENABLE_BD_MST132C_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST142A_D01A_S" {print "#define ENABLE_BD_MST142A_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST142B_D01A_S" {print "#define ENABLE_BD_MST142B_D01A_S " $3}
$2 == "ENABLE_MSTAR_AMBER_BD_MST142C_D01A_S" {print "#define ENABLE_BD_MST142C_D01A_S " $3}
$2 == "ENABLE_MSTAR_BD_MST142D_D01A_S" {print "#define ENABLE_BD_MST142D_D01A_S " $3}
$2 == "ENABLE_MSTAR_BD_MST147A_D01A_S" {print "#define ENABLE_BD_MST147A_D01A_S " $3}
$2 == "ENABLE_MSTAR_BD_MST147A_D01A_S_AGATE" {print "#define ENABLE_BD_MST147A_D01A_S_AGATE " $3}
$2 == "ENABLE_MSTAR_BD_MST147B_D01A_S_AGATE" {print "#define ENABLE_BD_MST147B_D01A_S_AGATE " $3}
$2 == "ENABLE_MSTAR_BD_MST142A_D01A_S_EAGLE" {print "#define ENABLE_BD_MST142A_D01A_S_EAGLE " $3}
$2 == "ENABLE_MSTAR_BD_MST142A_D01A_S_EIFFEL" {print "#define ENABLE_BD_MST142A_D01A_S_EIFFEL " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MST170A_D01A_S" {print "#define ENABLE_BD_MST170A_D01A_S " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MST170A_D01A" {print "#define ENABLE_BD_MST170A_D01A " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MST170B_D01A_S" {print "#define ENABLE_BD_MST170B_D01A_S " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MST170A_D02A" {print "#define ENABLE_BD_MST170A_D02A " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_D3C_L4D_V01" {print "#define ENABLE_BD_D3C_L4D_V01 " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_D3B_L2S_V01" {print "#define ENABLE_BD_D3B_L2S_V01 " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MP3050_SR1" {print "#define ENABLE_BD_MP3050_SR1 " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MP3050_SR2" {print "#define ENABLE_BD_MP3050_SR2 " $3}
$2 == "ENABLE_MSTAR_KAISER_BD_MST187A_D01A" {print "#define ENABLE_BD_MST187A_D01A " $3}
$2 == "ENABLE_MSTAR_KENYA_BD_FPGA" {print "#define ENABLE_KENYA_BD_FPGA " $3}
$2 == "ENABLE_MSTAR_KENYA_BD_MST188A_D01A_S" {print "#define ENABLE_KENYA_BD_MST188A_D01A_S " $3}
$2 == "ENABLE_MSTAR_KENYA_BD_MST188A_D01A" {print "#define ENABLE_KENYA_BD_MST188A_D01A " $3}
$2 == "ENABLE_MSTAR_KENYA_BD_MST188B_D01A_S" {print "#define ENABLE_KENYA_BD_MST188B_D01A_S " $3}
$2 == "ENABLE_MSTAR_KRITI_BD_FPGA" {print "#define ENABLE_KRITI_BD_FPGA " $3}
$2 == "ENABLE_MSTAR_KRITI_BD_MST204A_D01A_S_DDR2" {print "#define ENABLE_KRITI_BD_MST204A_D01A_S_DDR2 " $3}
$2 == "ENABLE_MSTAR_KRITI_BD_MST204A_D01A_DDR2" {print "#define ENABLE_KRITI_BD_MST204A_D01A_DDR2 " $3} 
$2 == "ENABLE_MSTAR_KRITI_BD_MST204A_D01A_S_DDR3" {print "#define ENABLE_KRITI_BD_MST204A_D01A_S_DDR3 " $3}
$2 == "ENABLE_MSTAR_KRITI_BD_MST204A_D01A_DDR3" {print "#define ENABLE_KRITI_BD_MST204A_D01A_DDR3 " $3} 
$2 == "ENABLE_MSTAR_TITANIA_MMAP_128MB_128MB_DEFAULT" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 128"; print "#define MSTAR_DRAM1_MB_SIZE 128"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_256MB_256MB_DEFAULT" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 256"; print "#define MSTAR_DRAM1_MB_SIZE 256"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_128MB_128MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 128"; print "#define MSTAR_DRAM1_MB_SIZE 128"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_128MB_256MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 128"; print "#define MSTAR_DRAM1_MB_SIZE 256"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_128MB_64MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 128"; print "#define MSTAR_DRAM1_MB_SIZE 64"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_64MB_128MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 64"; print "#define MSTAR_DRAM1_MB_SIZE 128"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_64MB_64MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 64"; print "#define MSTAR_DRAM1_MB_SIZE 64"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_128MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 128"; print "#define MSTAR_DRAM1_MB_SIZE 0"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_64MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 64"; print "#define MSTAR_DRAM1_MB_SIZE 0"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_512MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 512"; print "#define MSTAR_DRAM1_MB_SIZE 0"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_512MB_512MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 512"; print "#define MSTAR_DRAM1_MB_SIZE 512"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_256MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 256"; print "#define MSTAR_DRAM1_MB_SIZE 0"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_256MB_256MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 256"; print "#define MSTAR_DRAM1_MB_SIZE 256"}
$2 == "ENABLE_MSTAR_TITANIA_MMAP_512MB_256MB" && $3 == "1" {print "#define MSTAR_DRAM0_MB_SIZE 512"; print "#define MSTAR_DRAM1_MB_SIZE 256"}
$2 == "CONFIG_UBOOT_LOADADDR" {print "#define CONFIG_SYS_TEXT_BASE " $3}
$2 == "CONFIG_DRAM_SIZE_MB_RELOCATE" {print "#define CONFIG_DRAM_SIZE_MB_RELOCATE " $3}
$2 == "CONFIG_MSTAR_STR_ENABLE"  && $3=="1" {print "#define CONFIG_MSTAR_STR_ENABLE  1"}
$2 == "CONFIG_MSTAR_STR_ENABLE"  && $3!="1" {print "#define CONFIG_MSTAR_STR_ENABLE  0"}
$2 == "CONFIG_MIU0_BUSADDR" {print "#define CONFIG_MIU0_BUSADDR " $3}
$2 == "CONFIG_MIU1_BUSADDR" {print "#define CONFIG_MIU1_BUSADDR " $3}
$2 == "CONFIG_RELOCATION_INFO_ADDRESS" {print "#define RELOCATION_INFO_ADDRESS " $3}
$2 == "CONFIG_DYNAMIC_RELOCATE"  && $3=="1" {print "#define CONFIG_DYNAMIC_RELOCATE  1"}
$2 == "CONFIG_DYNAMIC_RELOCATE"  && $3=="1" {print "#define CONFIG_DYNAMIC_RELOCATE  1"}
$2 == "CONFIG_64BIT_TO_32BIT_MODE"  && $3=="1" {print "#define CONFIG_64BIT_TO_32BIT_MODE  1"}
