////////////////////////////////////////////////////////////////////////////////
//
// Copyright (c) 2006-2009 MStar Semiconductor, Inc.
// All rights reserved.
//
// Unless otherwise stipulated in writing, any and all information contained
// herein regardless in any format shall remain the sole proprietary of
// MStar Semiconductor Inc. and be kept in strict confidence
// ("MStar Confidential Information") by the recipient.
// Any unauthorized act including without limitation unauthorized disclosure,
// copying, use, reproduction, sale, distribution, modification, disassembling,
// reverse engineering and compiling of the contents of MStar Confidential
// Information is unlawful and strictly prohibited. MStar hereby reserves the
// rights to any and all damages, losses, costs and expenses resulting therefrom.
//
////////////////////////////////////////////////////////////////////////////////

// This file is generated by script, please do not edit it directly 
#ifndef _MSD8Z30ND_H_
#define _MSD8Z30ND_H_

#define PAD_NC 9999
#define PAD_GND 0

#define BALL_W2 PAD_GPIO_PM15
#define PAD_GPIO_PM15 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_W2_IS_GPIO
#define BALL_W2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO BALL_W2_IS_GPIO
#endif 

#define BALL_W3 PAD_GPIO_PM16
#define PAD_GPIO_PM16 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_W3_IS_GPIO
#define BALL_W3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM16_IS_GPIO
#define PAD_GPIO_PM16_IS_GPIO BALL_W3_IS_GPIO
#endif 

#define PAD_GPIO_PM17 9999
#ifndef PAD_GPIO_PM17_IS_GPIO
#define PAD_GPIO_PM17_IS_GPIO 0
#endif 

#define PAD_GPIO_PM18 9999
#ifndef PAD_GPIO_PM18_IS_GPIO
#define PAD_GPIO_PM18_IS_GPIO 0
#endif 

#define BALL_C5 PAD_VID0
#define PAD_VID0 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_B5 PAD_VID1
#define PAD_VID1 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_F3 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_F3_IS_GPIO
#define BALL_F3_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_F3_IS_GPIO
#endif 

#define PAD_AV_LNK 9999
#ifndef PAD_AV_LNK_IS_GPIO
#define PAD_AV_LNK_IS_GPIO 0
#endif 

#define BALL_J3 PAD_PWM_PM
#define PAD_PWM_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_J3_IS_GPIO
#define BALL_J3_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_J3_IS_GPIO
#endif 

#define PAD_DDCDA_CK 9999
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO 0
#endif 

#define BALL_W1 PAD_GPIO_PM14
#define PAD_GPIO_PM14 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_W1_IS_GPIO
#define BALL_W1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO BALL_W1_IS_GPIO
#endif 

#define PAD_DDCDA_DA 9999
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO 0
#endif 

#define PAD_DDCDD_DA 9999
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO 0
#endif 

#define BALL_J2 PAD_GPIO_PM1
#define PAD_GPIO_PM1 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_J2_IS_GPIO
#define BALL_J2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_J2_IS_GPIO
#endif 

#define BALL_AC4 PAD_CEC
#define PAD_CEC 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_AC4_IS_GPIO
#endif 

#define BALL_D1 PAD_GPIO_PM2
#define PAD_GPIO_PM2 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_N10 PAD_HOTPLUGA
#define PAD_HOTPLUGA 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_N10_IS_GPIO
#define BALL_N10_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_N10_IS_GPIO
#endif 

#define BALL_D2 PAD_GPIO_PM3
#define PAD_GPIO_PM3 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define BALL_K3 PAD_GPIO_PM4
#define PAD_GPIO_PM4 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_K3_IS_GPIO
#define BALL_K3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_K3_IS_GPIO
#endif 

#define BALL_J1 PAD_GPIO_PM5
#define PAD_GPIO_PM5 16
#define GPIO_PAD_16 GPIO15
#ifndef BALL_J1_IS_GPIO
#define BALL_J1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_J1_IS_GPIO
#endif 

#define BALL_AD4 PAD_HOTPLUGC
#define PAD_HOTPLUGC 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO BALL_AD4_IS_GPIO
#endif 

#define BALL_A2 PAD_GPIO_PM6
#define PAD_GPIO_PM6 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_A2_IS_GPIO
#endif 

#define BALL_P5 PAD_GPIO_PM7
#define PAD_GPIO_PM7 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_P5_IS_GPIO
#define BALL_P5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO BALL_P5_IS_GPIO
#endif 

#define PAD_DDCDB_CK 9999
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO 0
#endif 

#define PAD_DDCDD_CK 9999
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO 0
#endif 

#define PAD_DDCDB_DA 9999
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO 0
#endif 

#define BALL_P10 PAD_HOTPLUGD
#define PAD_HOTPLUGD 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_P10_IS_GPIO
#define BALL_P10_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_P10_IS_GPIO
#endif 

#define PAD_HOTPLUGB 9999
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO 0
#endif 

#define BALL_W5 PAD_DDCDC_CK
#define PAD_DDCDC_CK 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO BALL_W5_IS_GPIO
#endif 

#define BALL_W4 PAD_DDCDC_DA
#define PAD_DDCDC_DA 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_W4_IS_GPIO
#define BALL_W4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO BALL_W4_IS_GPIO
#endif 

#define BALL_AE4 PAD_GPIO17
#define PAD_GPIO17 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_AE4_IS_GPIO
#define BALL_AE4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO BALL_AE4_IS_GPIO
#endif 

#define PAD_GPIO28 9999
#ifndef PAD_GPIO28_IS_GPIO
#define PAD_GPIO28_IS_GPIO 0
#endif 

#define BALL_AD6 PAD_GPIO18
#define PAD_GPIO18 72
#define GPIO_PAD_72 GPIO71
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO BALL_AD6_IS_GPIO
#endif 

#define PAD_GPIO29 9999
#ifndef PAD_GPIO29_IS_GPIO
#define PAD_GPIO29_IS_GPIO 0
#endif 

#define BALL_K2 PAD_GPIO19
#define PAD_GPIO19 73
#define GPIO_PAD_73 GPIO72
#ifndef BALL_K2_IS_GPIO
#define BALL_K2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO BALL_K2_IS_GPIO
#endif 

#define PAD_GPIO30 9999
#ifndef PAD_GPIO30_IS_GPIO
#define PAD_GPIO30_IS_GPIO 0
#endif 

#define BALL_K1 PAD_GPIO20
#define PAD_GPIO20 74
#define GPIO_PAD_74 GPIO73
#ifndef BALL_K1_IS_GPIO
#define BALL_K1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO BALL_K1_IS_GPIO
#endif 

#define PAD_GPIO31 9999
#ifndef PAD_GPIO31_IS_GPIO
#define PAD_GPIO31_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO32 9999
#ifndef PAD_GPIO32_IS_GPIO
#define PAD_GPIO32_IS_GPIO 0
#endif 

#define BALL_AH5 PAD_GPIO26
#define PAD_GPIO26 80
#define GPIO_PAD_80 GPIO79
#ifndef BALL_AH5_IS_GPIO
#define BALL_AH5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO BALL_AH5_IS_GPIO
#endif 

#define PAD_GPIO33 9999
#ifndef PAD_GPIO33_IS_GPIO
#define PAD_GPIO33_IS_GPIO 0
#endif 

#define BALL_AG5 PAD_GPIO25
#define PAD_GPIO25 79
#define GPIO_PAD_79 GPIO78
#ifndef BALL_AG5_IS_GPIO
#define BALL_AG5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO BALL_AG5_IS_GPIO
#endif 

#define PAD_GPIO34 9999
#ifndef PAD_GPIO34_IS_GPIO
#define PAD_GPIO34_IS_GPIO 0
#endif 

#define BALL_AG1 PAD_GPIO24
#define PAD_GPIO24 78
#define GPIO_PAD_78 GPIO77
#ifndef BALL_AG1_IS_GPIO
#define BALL_AG1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO BALL_AG1_IS_GPIO
#endif 

#define PAD_GPIO35 9999
#ifndef PAD_GPIO35_IS_GPIO
#define PAD_GPIO35_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define BALL_AL30 PAD_GPIO36
#define PAD_GPIO36 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_AL30_IS_GPIO
#define BALL_AL30_IS_GPIO 0
#endif 
#ifndef PAD_GPIO36_IS_GPIO
#define PAD_GPIO36_IS_GPIO BALL_AL30_IS_GPIO
#endif 

#define BALL_AF5 PAD_GPIO21
#define PAD_GPIO21 75
#define GPIO_PAD_75 GPIO74
#ifndef BALL_AF5_IS_GPIO
#define BALL_AF5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO BALL_AF5_IS_GPIO
#endif 

#define BALL_AM30 PAD_GPIO37
#define PAD_GPIO37 91
#define GPIO_PAD_91 GPIO90
#ifndef BALL_AM30_IS_GPIO
#define BALL_AM30_IS_GPIO 0
#endif 
#ifndef PAD_GPIO37_IS_GPIO
#define PAD_GPIO37_IS_GPIO BALL_AM30_IS_GPIO
#endif 

#define BALL_AG2 PAD_GPIO23
#define PAD_GPIO23 77
#define GPIO_PAD_77 GPIO76
#ifndef BALL_AG2_IS_GPIO
#define BALL_AG2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO BALL_AG2_IS_GPIO
#endif 

#define BALL_AG3 PAD_TGPIO0
#define PAD_TGPIO0 170
#define GPIO_PAD_170 GPIO169
#ifndef BALL_AG3_IS_GPIO
#define BALL_AG3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AG3_IS_GPIO
#endif 

#define BALL_AH3 PAD_TGPIO1
#define PAD_TGPIO1 171
#define GPIO_PAD_171 GPIO170
#ifndef BALL_AH3_IS_GPIO
#define BALL_AH3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AH3_IS_GPIO
#endif 

#define BALL_AJ3 PAD_TGPIO2
#define PAD_TGPIO2 172
#define GPIO_PAD_172 GPIO171
#ifndef BALL_AJ3_IS_GPIO
#define BALL_AJ3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_AJ3_IS_GPIO
#endif 

#define BALL_AK2 PAD_TGPIO3
#define PAD_TGPIO3 173
#define GPIO_PAD_173 GPIO172
#ifndef BALL_AK2_IS_GPIO
#define BALL_AK2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_AK2_IS_GPIO
#endif 

#define BALL_AM7 PAD_GT_TX_CLK
#define PAD_GT_TX_CLK 218
#define GPIO_PAD_218 GPIO217
#ifndef BALL_AM7_IS_GPIO
#define BALL_AM7_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_CLK_IS_GPIO
#define PAD_GT_TX_CLK_IS_GPIO BALL_AM7_IS_GPIO
#endif 

#define BALL_AB15 PAD_PCM_CD_N
#define PAD_PCM_CD_N 150
#define GPIO_PAD_150 GPIO149
#ifndef BALL_AB15_IS_GPIO
#define BALL_AB15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO BALL_AB15_IS_GPIO
#endif 

#define BALL_AD14 PAD_PCM_D3
#define PAD_PCM_D3 118
#define GPIO_PAD_118 GPIO117
#ifndef BALL_AD14_IS_GPIO
#define BALL_AD14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_AD14_IS_GPIO
#endif 

#define BALL_AM4 PAD_GT_TX_CTL
#define PAD_GT_TX_CTL 223
#define GPIO_PAD_223 GPIO222
#ifndef BALL_AM4_IS_GPIO
#define BALL_AM4_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_CTL_IS_GPIO
#define PAD_GT_TX_CTL_IS_GPIO BALL_AM4_IS_GPIO
#endif 

#define BALL_AD15 PAD_PCM_D4
#define PAD_PCM_D4 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_AD15_IS_GPIO
#define BALL_AD15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_AD15_IS_GPIO
#endif 

#define BALL_AM6 PAD_GT_TX_D0
#define PAD_GT_TX_D0 219
#define GPIO_PAD_219 GPIO218
#ifndef BALL_AM6_IS_GPIO
#define BALL_AM6_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_D0_IS_GPIO
#define PAD_GT_TX_D0_IS_GPIO BALL_AM6_IS_GPIO
#endif 

#define BALL_AE16 PAD_PCM_D5
#define PAD_PCM_D5 120
#define GPIO_PAD_120 GPIO119
#ifndef BALL_AE16_IS_GPIO
#define BALL_AE16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_AE16_IS_GPIO
#endif 

#define BALL_AL6 PAD_GT_TX_D1
#define PAD_GT_TX_D1 220
#define GPIO_PAD_220 GPIO219
#ifndef BALL_AL6_IS_GPIO
#define BALL_AL6_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_D1_IS_GPIO
#define PAD_GT_TX_D1_IS_GPIO BALL_AL6_IS_GPIO
#endif 

#define BALL_AC17 PAD_PCM_D6
#define PAD_PCM_D6 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_AC17_IS_GPIO
#define BALL_AC17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_AC17_IS_GPIO
#endif 

#define BALL_AL5 PAD_GT_TX_D2
#define PAD_GT_TX_D2 221
#define GPIO_PAD_221 GPIO220
#ifndef BALL_AL5_IS_GPIO
#define BALL_AL5_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_D2_IS_GPIO
#define PAD_GT_TX_D2_IS_GPIO BALL_AL5_IS_GPIO
#endif 

#define BALL_AE13 PAD_PCM_D7
#define PAD_PCM_D7 122
#define GPIO_PAD_122 GPIO121
#ifndef BALL_AE13_IS_GPIO
#define BALL_AE13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_AE13_IS_GPIO
#endif 

#define BALL_AK5 PAD_GT_TX_D3
#define PAD_GT_TX_D3 222
#define GPIO_PAD_222 GPIO221
#ifndef BALL_AK5_IS_GPIO
#define BALL_AK5_IS_GPIO 0
#endif 
#ifndef PAD_GT_TX_D3_IS_GPIO
#define PAD_GT_TX_D3_IS_GPIO BALL_AK5_IS_GPIO
#endif 

#define BALL_AH10 PAD_PCM_CE_N
#define PAD_PCM_CE_N 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_AH10_IS_GPIO
#define BALL_AH10_IS_GPIO 0
#endif 
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO BALL_AH10_IS_GPIO
#endif 

#define BALL_AL7 PAD_GT_RX_CLK
#define PAD_GT_RX_CLK 217
#define GPIO_PAD_217 GPIO216
#ifndef BALL_AL7_IS_GPIO
#define BALL_AL7_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_CLK_IS_GPIO
#define PAD_GT_RX_CLK_IS_GPIO BALL_AL7_IS_GPIO
#endif 

#define BALL_AH15 PAD_PCM_A10
#define PAD_PCM_A10 124
#define GPIO_PAD_124 GPIO123
#ifndef BALL_AH15_IS_GPIO
#define BALL_AH15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_AH15_IS_GPIO
#endif 

#define BALL_AG10 PAD_PCM_OE_N
#define PAD_PCM_OE_N 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_AG10_IS_GPIO
#define BALL_AG10_IS_GPIO 0
#endif 
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO BALL_AG10_IS_GPIO
#endif 

#define BALL_AH12 PAD_PCM_IORD_N
#define PAD_PCM_IORD_N 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_AH12_IS_GPIO
#define BALL_AH12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO BALL_AH12_IS_GPIO
#endif 

#define BALL_AL10 PAD_GT_RX_CTL
#define PAD_GT_RX_CTL 212
#define GPIO_PAD_212 GPIO211
#ifndef BALL_AL10_IS_GPIO
#define BALL_AL10_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_CTL_IS_GPIO
#define PAD_GT_RX_CTL_IS_GPIO BALL_AL10_IS_GPIO
#endif 

#define BALL_AJ14 PAD_PCM_A11
#define PAD_PCM_A11 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_AJ14_IS_GPIO
#define BALL_AJ14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_AJ14_IS_GPIO
#endif 

#define BALL_AK9 PAD_GT_RX_D0
#define PAD_GT_RX_D0 213
#define GPIO_PAD_213 GPIO212
#ifndef BALL_AK9_IS_GPIO
#define BALL_AK9_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_D0_IS_GPIO
#define PAD_GT_RX_D0_IS_GPIO BALL_AK9_IS_GPIO
#endif 

#define BALL_AG11 PAD_PCM_IOWR_N
#define PAD_PCM_IOWR_N 129
#define GPIO_PAD_129 GPIO128
#ifndef BALL_AG11_IS_GPIO
#define BALL_AG11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO BALL_AG11_IS_GPIO
#endif 

#define BALL_AM9 PAD_GT_RX_D1
#define PAD_GT_RX_D1 214
#define GPIO_PAD_214 GPIO213
#ifndef BALL_AM9_IS_GPIO
#define BALL_AM9_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_D1_IS_GPIO
#define PAD_GT_RX_D1_IS_GPIO BALL_AM9_IS_GPIO
#endif 

#define BALL_AE15 PAD_PCM_A1
#define PAD_PCM_A1 144
#define GPIO_PAD_144 GPIO143
#ifndef BALL_AE15_IS_GPIO
#define BALL_AE15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AE15_IS_GPIO
#endif 

#define BALL_AM2 PAD_GT_FR_CLK
#define PAD_GT_FR_CLK 226
#define GPIO_PAD_226 GPIO225
#ifndef BALL_AM2_IS_GPIO
#define BALL_AM2_IS_GPIO 0
#endif 
#ifndef PAD_GT_FR_CLK_IS_GPIO
#define PAD_GT_FR_CLK_IS_GPIO BALL_AM2_IS_GPIO
#endif 

#define BALL_AK8 PAD_GT_RX_D2
#define PAD_GT_RX_D2 215
#define GPIO_PAD_215 GPIO214
#ifndef BALL_AK8_IS_GPIO
#define BALL_AK8_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_D2_IS_GPIO
#define PAD_GT_RX_D2_IS_GPIO BALL_AK8_IS_GPIO
#endif 

#define BALL_AH14 PAD_PCM_A9
#define PAD_PCM_A9 128
#define GPIO_PAD_128 GPIO127
#ifndef BALL_AH14_IS_GPIO
#define BALL_AH14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_AH14_IS_GPIO
#endif 

#define BALL_AL8 PAD_GT_RX_D3
#define PAD_GT_RX_D3 216
#define GPIO_PAD_216 GPIO215
#ifndef BALL_AL8_IS_GPIO
#define BALL_AL8_IS_GPIO 0
#endif 
#ifndef PAD_GT_RX_D3_IS_GPIO
#define PAD_GT_RX_D3_IS_GPIO BALL_AL8_IS_GPIO
#endif 

#define BALL_AK4 PAD_GT_MDC
#define PAD_GT_MDC 224
#define GPIO_PAD_224 GPIO223
#ifndef BALL_AK4_IS_GPIO
#define BALL_AK4_IS_GPIO 0
#endif 
#ifndef PAD_GT_MDC_IS_GPIO
#define PAD_GT_MDC_IS_GPIO BALL_AK4_IS_GPIO
#endif 

#define BALL_AG14 PAD_PCM_A8
#define PAD_PCM_A8 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_AG14_IS_GPIO
#define BALL_AG14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_AG14_IS_GPIO
#endif 

#define BALL_AL3 PAD_GT_MDIO
#define PAD_GT_MDIO 225
#define GPIO_PAD_225 GPIO224
#ifndef BALL_AL3_IS_GPIO
#define BALL_AL3_IS_GPIO 0
#endif 
#ifndef PAD_GT_MDIO_IS_GPIO
#define PAD_GT_MDIO_IS_GPIO BALL_AL3_IS_GPIO
#endif 

#define BALL_AF14 PAD_PCM_A13
#define PAD_PCM_A13 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AF14_IS_GPIO
#define BALL_AF14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_AF14_IS_GPIO
#endif 

#define BALL_AF15 PAD_PCM_A14
#define PAD_PCM_A14 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AF15_IS_GPIO
#define BALL_AF15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_AF15_IS_GPIO
#endif 

#define BALL_AH11 PAD_PCM_WE_N
#define PAD_PCM_WE_N 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AH11_IS_GPIO
#define BALL_AH11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO BALL_AH11_IS_GPIO
#endif 

#define BALL_AM15 PAD_TS0_D4
#define PAD_TS0_D4 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_AM15_IS_GPIO
#define BALL_AM15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_AM15_IS_GPIO
#endif 

#define BALL_AJ11 PAD_PCM_IRQA_N
#define PAD_PCM_IRQA_N 134
#define GPIO_PAD_134 GPIO133
#ifndef BALL_AJ11_IS_GPIO
#define BALL_AJ11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO BALL_AJ11_IS_GPIO
#endif 

#define BALL_AL15 PAD_TS0_D5
#define PAD_TS0_D5 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_AL15_IS_GPIO
#define BALL_AL15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_AL15_IS_GPIO
#endif 

#define BALL_AF13 PAD_PCM_A12
#define PAD_PCM_A12 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AF13_IS_GPIO
#define BALL_AF13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_AF13_IS_GPIO
#endif 

#define BALL_AL14 PAD_TS0_D6
#define PAD_TS0_D6 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_AL14_IS_GPIO
#define BALL_AL14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_AL14_IS_GPIO
#endif 

#define BALL_AH13 PAD_PCM_A7
#define PAD_PCM_A7 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AH13_IS_GPIO
#define BALL_AH13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AH13_IS_GPIO
#endif 

#define BALL_AK14 PAD_TS0_D7
#define PAD_TS0_D7 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_AK14_IS_GPIO
#define BALL_AK14_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_AK14_IS_GPIO
#endif 

#define BALL_AG12 PAD_PCM_A6
#define PAD_PCM_A6 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AG12_IS_GPIO
#define BALL_AG12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AG12_IS_GPIO
#endif 

#define BALL_AK15 PAD_TS0_D3
#define PAD_TS0_D3 177
#define GPIO_PAD_177 GPIO176
#ifndef BALL_AK15_IS_GPIO
#define BALL_AK15_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_AK15_IS_GPIO
#endif 

#define BALL_AJ13 PAD_PCM_A5
#define PAD_PCM_A5 138
#define GPIO_PAD_138 GPIO137
#ifndef BALL_AJ13_IS_GPIO
#define BALL_AJ13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AJ13_IS_GPIO
#endif 

#define BALL_AM13 PAD_TS0_CLK
#define PAD_TS0_CLK 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_AM13_IS_GPIO
#define BALL_AM13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_AM13_IS_GPIO
#endif 

#define BALL_AB14 PAD_PCM_RESET
#define PAD_PCM_RESET 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_AB14_IS_GPIO
#define BALL_AB14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO BALL_AB14_IS_GPIO
#endif 

#define BALL_AL13 PAD_TS0_VLD
#define PAD_TS0_VLD 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_AL13_IS_GPIO
#define BALL_AL13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_AL13_IS_GPIO
#endif 

#define BALL_AG13 PAD_PCM_A4
#define PAD_PCM_A4 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_AG13_IS_GPIO
#define BALL_AG13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AG13_IS_GPIO
#endif 

#define BALL_AK13 PAD_TS0_SYNC
#define PAD_TS0_SYNC 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_AK13_IS_GPIO
#define BALL_AK13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_AK13_IS_GPIO
#endif 

#define BALL_AD16 PAD_PCM_WAIT_N
#define PAD_PCM_WAIT_N 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_AD16_IS_GPIO
#define BALL_AD16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO BALL_AD16_IS_GPIO
#endif 

#define BALL_AK16 PAD_TS0_D0
#define PAD_TS0_D0 174
#define GPIO_PAD_174 GPIO173
#ifndef BALL_AK16_IS_GPIO
#define BALL_AK16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_AK16_IS_GPIO
#endif 

#define BALL_AD17 PAD_PCM_A3
#define PAD_PCM_A3 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_AD17_IS_GPIO
#define BALL_AD17_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AD17_IS_GPIO
#endif 

#define BALL_AL16 PAD_TS0_D1
#define PAD_TS0_D1 175
#define GPIO_PAD_175 GPIO174
#ifndef BALL_AL16_IS_GPIO
#define BALL_AL16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_AL16_IS_GPIO
#endif 

#define BALL_AF16 PAD_PCM_A2
#define PAD_PCM_A2 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_AF16_IS_GPIO
#define BALL_AF16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AF16_IS_GPIO
#endif 

#define BALL_AM16 PAD_TS0_D2
#define PAD_TS0_D2 176
#define GPIO_PAD_176 GPIO175
#ifndef BALL_AM16_IS_GPIO
#define BALL_AM16_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_AM16_IS_GPIO
#endif 

#define BALL_AC16 PAD_PCM_REG_N
#define PAD_PCM_REG_N 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_AC16_IS_GPIO
#define BALL_AC16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO BALL_AC16_IS_GPIO
#endif 

#define BALL_AL18 PAD_TS1_SYNC
#define PAD_TS1_SYNC 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_AL18_IS_GPIO
#define BALL_AL18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_AL18_IS_GPIO
#endif 

#define BALL_AE14 PAD_PCM_A0
#define PAD_PCM_A0 145
#define GPIO_PAD_145 GPIO144
#ifndef BALL_AE14_IS_GPIO
#define BALL_AE14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_AE14_IS_GPIO
#endif 

#define BALL_AH16 PAD_TS1_D0
#define PAD_TS1_D0 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_AH16_IS_GPIO
#define BALL_AH16_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_AH16_IS_GPIO
#endif 

#define BALL_AC15 PAD_PCM_D0
#define PAD_PCM_D0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_AC15_IS_GPIO
#define BALL_AC15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_AC15_IS_GPIO
#endif 

#define BALL_AB16 PAD_PCM_D1
#define PAD_PCM_D1 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_AB16_IS_GPIO
#define BALL_AB16_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_AB16_IS_GPIO
#endif 

#define BALL_AL17 PAD_TS1_D5
#define PAD_TS1_D5 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_AL17_IS_GPIO
#define BALL_AL17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_AL17_IS_GPIO
#endif 

#define BALL_AD13 PAD_PCM_D2
#define PAD_PCM_D2 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_AD13_IS_GPIO
#define BALL_AD13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_AD13_IS_GPIO
#endif 

#define BALL_AK18 PAD_TS1_D1
#define PAD_TS1_D1 194
#define GPIO_PAD_194 GPIO193
#ifndef BALL_AK18_IS_GPIO
#define BALL_AK18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_AK18_IS_GPIO
#endif 

#define BALL_AJ15 PAD_PCM2_WAIT_N
#define PAD_PCM2_WAIT_N 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_AJ15_IS_GPIO
#define BALL_AJ15_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO BALL_AJ15_IS_GPIO
#endif 

#define BALL_AM18 PAD_TS1_D2
#define PAD_TS1_D2 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_AM18_IS_GPIO
#define BALL_AM18_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AM18_IS_GPIO
#endif 

#define BALL_AG15 PAD_PCM2_RESET
#define PAD_PCM2_RESET 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_AG15_IS_GPIO
#define BALL_AG15_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO BALL_AG15_IS_GPIO
#endif 

#define BALL_AH17 PAD_TS1_D3
#define PAD_TS1_D3 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_AH17_IS_GPIO
#define BALL_AH17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_AH17_IS_GPIO
#endif 

#define BALL_AG17 PAD_PCM2_CE_N
#define PAD_PCM2_CE_N 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_AG17_IS_GPIO
#define BALL_AG17_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO BALL_AG17_IS_GPIO
#endif 

#define BALL_AG16 PAD_PCM2_IRQA_N
#define PAD_PCM2_IRQA_N 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_AG16_IS_GPIO
#define BALL_AG16_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO BALL_AG16_IS_GPIO
#endif 

#define BALL_AL19 PAD_TS1_VLD
#define PAD_TS1_VLD 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_AL19_IS_GPIO
#define BALL_AL19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_AL19_IS_GPIO
#endif 

#define PAD_DIM3 9999
#ifndef PAD_DIM3_IS_GPIO
#define PAD_DIM3_IS_GPIO 0
#endif 

#define BALL_AK17 PAD_TS1_D4
#define PAD_TS1_D4 191
#define GPIO_PAD_191 GPIO190
#ifndef BALL_AK17_IS_GPIO
#define BALL_AK17_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_AK17_IS_GPIO
#endif 

#define PAD_DIM2 9999
#ifndef PAD_DIM2_IS_GPIO
#define PAD_DIM2_IS_GPIO 0
#endif 

#define BALL_AM19 PAD_TS1_CLK
#define PAD_TS1_CLK 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_AM19_IS_GPIO
#define BALL_AM19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_AM19_IS_GPIO
#endif 

#define PAD_DIM1 9999
#ifndef PAD_DIM1_IS_GPIO
#define PAD_DIM1_IS_GPIO 0
#endif 

#define BALL_AK19 PAD_TS1_D6
#define PAD_TS1_D6 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_AK19_IS_GPIO
#define BALL_AK19_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_AK19_IS_GPIO
#endif 

#define PAD_DIM0 9999
#ifndef PAD_DIM0_IS_GPIO
#define PAD_DIM0_IS_GPIO 0
#endif 

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif 

#define BALL_AL20 PAD_TS1_D7
#define PAD_TS1_D7 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_AL20_IS_GPIO
#define BALL_AL20_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_AL20_IS_GPIO
#endif 

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif 

#define PAD_SPI1_CK 9999
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO 0
#endif 

#define BALL_AJ28 PAD_VSYNC_LIKE
#define PAD_VSYNC_LIKE 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AJ28_IS_GPIO
#define BALL_AJ28_IS_GPIO 0
#endif 
#ifndef PAD_VSYNC_LIKE_IS_GPIO
#define PAD_VSYNC_LIKE_IS_GPIO BALL_AJ28_IS_GPIO
#endif 

#define BALL_AH29 PAD_SPI1_DI
#define PAD_SPI1_DI 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AH29_IS_GPIO
#define BALL_AH29_IS_GPIO 0
#endif 
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO BALL_AH29_IS_GPIO
#endif 

#define BALL_AK24 PAD_TS2_D0
#define PAD_TS2_D0 208
#define GPIO_PAD_208 GPIO207
#ifndef BALL_AK24_IS_GPIO
#define BALL_AK24_IS_GPIO 0
#endif 
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO BALL_AK24_IS_GPIO
#endif 

#define BALL_AM21 PAD_EMMC_RSTN
#define PAD_EMMC_RSTN 205
#define GPIO_PAD_205 GPIO204
#ifndef BALL_AM21_IS_GPIO
#define BALL_AM21_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_RSTN_IS_GPIO
#define PAD_EMMC_RSTN_IS_GPIO BALL_AM21_IS_GPIO
#endif 

#define BALL_AM24 PAD_TS2_VLD
#define PAD_TS2_VLD 209
#define GPIO_PAD_209 GPIO208
#ifndef BALL_AM24_IS_GPIO
#define BALL_AM24_IS_GPIO 0
#endif 
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO BALL_AM24_IS_GPIO
#endif 

#define BALL_AM22 PAD_EMMC_CLK
#define PAD_EMMC_CLK 206
#define GPIO_PAD_206 GPIO205
#ifndef BALL_AM22_IS_GPIO
#define BALL_AM22_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_CLK_IS_GPIO
#define PAD_EMMC_CLK_IS_GPIO BALL_AM22_IS_GPIO
#endif 

#define BALL_AK23 PAD_TS2_SYNC
#define PAD_TS2_SYNC 210
#define GPIO_PAD_210 GPIO209
#ifndef BALL_AK23_IS_GPIO
#define BALL_AK23_IS_GPIO 0
#endif 
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO BALL_AK23_IS_GPIO
#endif 

#define BALL_AL22 PAD_EMMC_CMD
#define PAD_EMMC_CMD 207
#define GPIO_PAD_207 GPIO206
#ifndef BALL_AL22_IS_GPIO
#define BALL_AL22_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_CMD_IS_GPIO
#define PAD_EMMC_CMD_IS_GPIO BALL_AL22_IS_GPIO
#endif 

#define BALL_AL23 PAD_TS2_CLK
#define PAD_TS2_CLK 211
#define GPIO_PAD_211 GPIO210
#ifndef BALL_AL23_IS_GPIO
#define BALL_AL23_IS_GPIO 0
#endif 
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO BALL_AL23_IS_GPIO
#endif 

#define BALL_AG20 PAD_NAND_CEZ1
#define PAD_NAND_CEZ1 197
#define GPIO_PAD_197 GPIO196
#ifndef BALL_AG20_IS_GPIO
#define BALL_AG20_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ1_IS_GPIO
#define PAD_NAND_CEZ1_IS_GPIO BALL_AG20_IS_GPIO
#endif 

#define BALL_AL21 PAD_PCM2_CD_N
#define PAD_PCM2_CD_N 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_AL21_IS_GPIO
#define BALL_AL21_IS_GPIO 0
#endif 
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO BALL_AL21_IS_GPIO
#endif 

#define BALL_AH20 PAD_NAND_CEZ
#define PAD_NAND_CEZ 196
#define GPIO_PAD_196 GPIO195
#ifndef BALL_AH20_IS_GPIO
#define BALL_AH20_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO BALL_AH20_IS_GPIO
#endif 

#define BALL_AL25 PAD_NAND_DQS
#define PAD_NAND_DQS 204
#define GPIO_PAD_204 GPIO203
#ifndef BALL_AL25_IS_GPIO
#define BALL_AL25_IS_GPIO 0
#endif 
#ifndef PAD_NAND_DQS_IS_GPIO
#define PAD_NAND_DQS_IS_GPIO BALL_AL25_IS_GPIO
#endif 

#define BALL_AJ22 PAD_NAND_CLE
#define PAD_NAND_CLE 198
#define GPIO_PAD_198 GPIO197
#ifndef BALL_AJ22_IS_GPIO
#define BALL_AJ22_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO BALL_AJ22_IS_GPIO
#endif 

#define BALL_AH19 PAD_NAND_REZ
#define PAD_NAND_REZ 199
#define GPIO_PAD_199 GPIO198
#ifndef BALL_AH19_IS_GPIO
#define BALL_AH19_IS_GPIO 0
#endif 
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO BALL_AH19_IS_GPIO
#endif 

#define BALL_AG21 PAD_NAND_WEZ
#define PAD_NAND_WEZ 200
#define GPIO_PAD_200 GPIO199
#ifndef BALL_AG21_IS_GPIO
#define BALL_AG21_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO BALL_AG21_IS_GPIO
#endif 

#define BALL_AH22 PAD_NAND_WPZ
#define PAD_NAND_WPZ 201
#define GPIO_PAD_201 GPIO200
#ifndef BALL_AH22_IS_GPIO
#define BALL_AH22_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO BALL_AH22_IS_GPIO
#endif 

#define BALL_AH21 PAD_NAND_ALE
#define PAD_NAND_ALE 202
#define GPIO_PAD_202 GPIO201
#ifndef BALL_AH21_IS_GPIO
#define BALL_AH21_IS_GPIO 0
#endif 
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO BALL_AH21_IS_GPIO
#endif 

#define BALL_AG19 PAD_NAND_RBZ
#define PAD_NAND_RBZ 203
#define GPIO_PAD_203 GPIO202
#ifndef BALL_AG19_IS_GPIO
#define BALL_AG19_IS_GPIO 0
#endif 
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO BALL_AG19_IS_GPIO
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif 

#define PAD_TCON8 9999
#ifndef PAD_TCON8_IS_GPIO
#define PAD_TCON8_IS_GPIO 0
#endif 

#define PAD_TCON2 9999
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO 0
#endif 

#define PAD_TCON9 9999
#ifndef PAD_TCON9_IS_GPIO
#define PAD_TCON9_IS_GPIO 0
#endif 

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif 

#define PAD_TCON10 9999
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO 0
#endif 

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif 

#define PAD_TCON11 9999
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO 0
#endif 

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif 

#define PAD_TCON12 9999
#ifndef PAD_TCON12_IS_GPIO
#define PAD_TCON12_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define BALL_G1 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_G1_IS_GPIO
#define BALL_G1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_G1_IS_GPIO
#endif 

#define BALL_H8 PAD_DDCR_CK
#define PAD_DDCR_CK 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_H8_IS_GPIO
#define BALL_H8_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_H8_IS_GPIO
#endif 

#define BALL_G2 PAD_I2S_OUT_SD1
#define PAD_I2S_OUT_SD1 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_G2_IS_GPIO
#define BALL_G2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO BALL_G2_IS_GPIO
#endif 

#define BALL_H3 PAD_I2S_OUT_SD2
#define PAD_I2S_OUT_SD2 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_H3_IS_GPIO
#define BALL_H3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO BALL_H3_IS_GPIO
#endif 

#define BALL_H7 PAD_DDCR_DA
#define PAD_DDCR_DA 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_H7_IS_GPIO
#define BALL_H7_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_H7_IS_GPIO
#endif 

#define BALL_H2 PAD_I2S_OUT_SD3
#define PAD_I2S_OUT_SD3 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_H2_IS_GPIO
#define BALL_H2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO BALL_H2_IS_GPIO
#endif 

#define BALL_G3 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_G3_IS_GPIO
#define BALL_G3_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_G3_IS_GPIO
#endif 

#define BALL_J4 PAD_PWM0
#define PAD_PWM0 151
#define GPIO_PAD_151 GPIO150
#ifndef BALL_J4_IS_GPIO
#define BALL_J4_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_J4_IS_GPIO
#endif 

#define BALL_F2 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 98
#define GPIO_PAD_98 GPIO97
#ifndef BALL_F2_IS_GPIO
#define BALL_F2_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_F2_IS_GPIO
#endif 

#define BALL_J6 PAD_PWM1
#define PAD_PWM1 152
#define GPIO_PAD_152 GPIO151
#ifndef BALL_J6_IS_GPIO
#define BALL_J6_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_J6_IS_GPIO
#endif 

#define BALL_F1 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 97
#define GPIO_PAD_97 GPIO96
#ifndef BALL_F1_IS_GPIO
#define BALL_F1_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_F1_IS_GPIO
#endif 

#define BALL_B1 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 96
#define GPIO_PAD_96 GPIO95
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_K5 PAD_PWM2
#define PAD_PWM2 153
#define GPIO_PAD_153 GPIO152
#ifndef BALL_K5_IS_GPIO
#define BALL_K5_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_K5_IS_GPIO
#endif 

#define BALL_C1 PAD_SPDIF_IN
#define PAD_SPDIF_IN 95
#define GPIO_PAD_95 GPIO94
#ifndef BALL_C1_IS_GPIO
#define BALL_C1_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_C1_IS_GPIO
#endif 

#define BALL_J5 PAD_PWM3
#define PAD_PWM3 154
#define GPIO_PAD_154 GPIO153
#ifndef BALL_J5_IS_GPIO
#define BALL_J5_IS_GPIO 0
#endif 
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_J5_IS_GPIO
#endif 

#define PAD_TCON13 9999
#ifndef PAD_TCON13_IS_GPIO
#define PAD_TCON13_IS_GPIO 0
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define BALL_K9 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 92
#define GPIO_PAD_92 GPIO91
#ifndef BALL_K9_IS_GPIO
#define BALL_K9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_K9_IS_GPIO
#endif 

#define BALL_E3 PAD_GPIO2
#define PAD_GPIO2 56
#define GPIO_PAD_56 GPIO55
#ifndef BALL_E3_IS_GPIO
#define BALL_E3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO BALL_E3_IS_GPIO
#endif 

#define BALL_H9 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 94
#define GPIO_PAD_94 GPIO93
#ifndef BALL_H9_IS_GPIO
#define BALL_H9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_H9_IS_GPIO
#endif 

#define BALL_B4 PAD_GPIO4
#define PAD_GPIO4 58
#define GPIO_PAD_58 GPIO57
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define BALL_J9 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 93
#define GPIO_PAD_93 GPIO92
#ifndef BALL_J9_IS_GPIO
#define BALL_J9_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_J9_IS_GPIO
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO8 9999
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO 0
#endif 

#define BALL_C4 PAD_GPIO3
#define PAD_GPIO3 57
#define GPIO_PAD_57 GPIO56
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define PAD_GPIO10 9999
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO12 9999
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO 0
#endif 

#define PAD_GPIO7 9999
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO 0
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_GPIO9 9999
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_GPIO11 9999
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define BALL_T5 PAD_SAR0
#define PAD_SAR0 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_T5_IS_GPIO
#define BALL_T5_IS_GPIO 0
#endif 
#ifndef PAD_SAR0_IS_GPIO
#define PAD_SAR0_IS_GPIO BALL_T5_IS_GPIO
#endif 

#define BALL_R5 PAD_SAR1
#define PAD_SAR1 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_R5_IS_GPIO
#define BALL_R5_IS_GPIO 0
#endif 
#ifndef PAD_SAR1_IS_GPIO
#define PAD_SAR1_IS_GPIO BALL_R5_IS_GPIO
#endif 

#define BALL_T6 PAD_SAR2
#define PAD_SAR2 46
#define GPIO_PAD_46 GPIO45
#ifndef BALL_T6_IS_GPIO
#define BALL_T6_IS_GPIO 0
#endif 
#ifndef PAD_SAR2_IS_GPIO
#define PAD_SAR2_IS_GPIO BALL_T6_IS_GPIO
#endif 

#define BALL_T4 PAD_SAR3
#define PAD_SAR3 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_T4_IS_GPIO
#define BALL_T4_IS_GPIO 0
#endif 
#ifndef PAD_SAR3_IS_GPIO
#define PAD_SAR3_IS_GPIO BALL_T4_IS_GPIO
#endif 

#define PAD_SAR4 9999
#ifndef PAD_SAR4_IS_GPIO
#define PAD_SAR4_IS_GPIO 0
#endif 

#define BALL_V3 PAD_WOL_INT
#define PAD_WOL_INT 51
#define GPIO_PAD_51 GPIO50
#ifndef BALL_V3_IS_GPIO
#define BALL_V3_IS_GPIO 0
#endif 
#ifndef PAD_WOL_INT_IS_GPIO
#define PAD_WOL_INT_IS_GPIO BALL_V3_IS_GPIO
#endif 

#define BALL_P7 PAD_LED0
#define PAD_LED0 30
#define GPIO_PAD_30 GPIO29
#ifndef BALL_P7_IS_GPIO
#define BALL_P7_IS_GPIO 0
#endif 
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_P7_IS_GPIO
#endif 

#define BALL_P6 PAD_LED1
#define PAD_LED1 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_P6_IS_GPIO
#define BALL_P6_IS_GPIO 0
#endif 
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_P6_IS_GPIO
#endif 

#define BALL_A3 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define BALL_K8 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_K8_IS_GPIO
#define BALL_K8_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_K8_IS_GPIO
#endif 

#define BALL_C3 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_B3 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B3_IS_GPIO
#define BALL_B3_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_B3_IS_GPIO
#endif 

#define BALL_J7 PAD_DDCA_CK
#define PAD_DDCA_CK 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_J7_IS_GPIO
#define BALL_J7_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_J7_IS_GPIO
#endif 

#define BALL_J8 PAD_DDCA_DA
#define PAD_DDCA_DA 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_J8_IS_GPIO
#define BALL_J8_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_J8_IS_GPIO
#endif 

#define BALL_N3 PAD_GPIO_PM0
#define PAD_GPIO_PM0 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_N3_IS_GPIO
#define BALL_N3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_N3_IS_GPIO
#endif 

#define BALL_M1 PAD_GPIO_PM8
#define PAD_GPIO_PM8 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_M1_IS_GPIO
#define BALL_M1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_M1_IS_GPIO
#endif 

#define BALL_D3 PAD_GPIO_PM9
#define PAD_GPIO_PM9 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define BALL_B2 PAD_GPIO_PM10
#define PAD_GPIO_PM10 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_P4 PAD_GPIO_PM11
#define PAD_GPIO_PM11 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_P4_IS_GPIO
#define BALL_P4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO BALL_P4_IS_GPIO
#endif 

#define BALL_C2 PAD_GPIO_PM12
#define PAD_GPIO_PM12 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define BALL_E2 PAD_GPIO_PM13
#define PAD_GPIO_PM13 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_E2_IS_GPIO
#define BALL_E2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO BALL_E2_IS_GPIO
#endif 


// PADS group name to index
#define PADS_DDCR           1223
#define PADS_DDCR2          1224
#define PADS_TS0            1225
#define PADS_TS1            1226
#define PADS_GPIO1_GPIO2    1227
#define PADS_LHSYNC2_LVSYNC2 1228
#define PADS_PCI_AD20_AD21  1229
#define PADS_PCI            1230
#define PADS_PCM            1231
#define PADS_SAR            1232
#define PADS_DOUT           1233
#define PADS_DIN            1234
#define PADS_I2S            1235
#define PADS_PF             1236
#define PADS_EMAC           1237
#define PADS_TCON           1238
#define PADS_UART1_MODE1    1239
#define PADS_UART1_MODE2    1240
#define PADS_UART1_MODE3    1241
#define PADS_UART2_MODE1    1242
#define PADS_UART2_MODE2    1243
#define PADS_UART2_MODE3    1244
#define PADS_ET_MODE0       1245
#define PADS_ET_MODE1       1246
#define PADS_ET_MODE2       1247
#define PADS_ET_MODE3       1248
#define PADS_MIIC           1249
#define PADS_PF_MODE1       1250
#define PADS_PF_MODE2       1251
#define PADS_PF_MODE3       1252
#define PADS_SPI_CZ1        1253
#define PADS_SPI_CZ2        1254
#define PADS_SPI_CZ3        1255
#define PADS_DDCR3          1256

// chip capbilities
#define CHIP_HAS_BT656_IN          0
#define CHIP_HAS_TS0               1
#define CHIP_HAS_TS1               0 
#define CHIP_HAS_LVDS_10BIT_X2     1
#define CHIP_HAS_LVDS_8BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X1      1
#define CHIP_HAS_CIMAX             0
#define CHIP_HAS_USB_P0            1
#define CHIP_HAS_USB_P1            1
#define CHIP_HAS_USBVBUS0          0
#define CHIP_HAS_USBVBUS1          0
#define CHIP_HAS_UART1_MODE1       1 
#define CHIP_HAS_UART1_MODE2       1
#define CHIP_HAS_UART1_MODE3       1 
#define CHIP_HAS_PCMCIA1           0
#define CHIP_HAS_PCMCIA2           0
#define CHIP_HAS_PCMCIA            0
#define CHIP_HAS_UART2_MODE1       1 
#define CHIP_HAS_UART2_MODE2       1 
#define CHIP_HAS_UART2_MODE3       1 
#define CHIP_HAS_RGB_A             1 
#define CHIP_HAS_RGB_B             1 
#define CHIP_HAS_RGB_C             1 
#define CHIP_HAS_HDMI_A            1 
#define CHIP_HAS_HDMI_B            1 
#define CHIP_HAS_HDMI_C            1 
#define CHIP_HAS_SPI_CZ1           1 
#define CHIP_HAS_SPI_CZ2           0 
#define CHIP_HAS_SPI_CZ3           0
#define CHIP_HAS_DDCR              1 
#define CHIP_HAS_DDCR2             1 
#define CHIP_HAS_TCON              1
#define CHIP_HAS_ET_MODE0_MII      1 
#define CHIP_HAS_ET_MODE0_RMII     1 
#define CHIP_HAS_ET_MODE1_MII      1 
#define CHIP_HAS_ET_MODE1_RMII     1 
#define CHIP_HAS_ET_MODE2_MII      1
#define CHIP_HAS_ET_MODE2_RMII     1
#define CHIP_HAS_I2S_IN            1 
#define CHIP_HAS_I2S_OUT           1
#define CHIP_HAS_SPDIF_IN          0 
#define CHIP_HAS_SPDIF_OUT         1
#define CHIP_HAS_DDR_A_CMD         1
#define CHIP_HAS_DDR_A_DATA        1
#define CHIP_HAS_DDR_B_CMD         1
#define CHIP_HAS_DDR_B_DATA        1
#define CHIP_USE_PCM_CDN_IN_PCM2   0
#define CHIP_USE_I2S_IN_IN_PCM     0
#define CHIP_USE_I2S_OUT_IN_PCM    0
#define CHIP_USE_SPDIF_IN_IN_PCM   0
#define CHIP_USE_SPDIF_OUT_IN_PCM  0
#define CHIP_USE_IIC_IN_DDCR2      0
#define CHIP_USE_PWM2_IN_GPIO14    0
#define CHIP_USE_PWM3_IN_GPIO15    0

// chip additional information
#define CHIP_FAMILY_TYPE           CHIP_FAMILY_NAPOLI

#endif /* _MSD8Z30ND_H_*/
