//<MStar Software>
//******************************************************************************
// MStar Software
// Copyright (c) 2010 - 2012 MStar Semiconductor, Inc. All rights reserved.
// All software, firmware and related documentation herein ("MStar Software") are
// intellectual property of MStar Semiconductor, Inc. ("MStar") and protected by
// law, including, but not limited to, copyright law and international treaties.
// Any use, modification, reproduction, retransmission, or republication of all 
// or part of MStar Software is expressly prohibited, unless prior written 
// permission has been granted by MStar. 
//
// By accessing, browsing and/or using MStar Software, you acknowledge that you
// have read, understood, and agree, to be bound by below terms ("Terms") and to
// comply with all applicable laws and regulations:
//
// 1. MStar shall retain any and all right, ownership and interest to MStar
//    Software and any modification/derivatives thereof.
//    No right, ownership, or interest to MStar Software and any
//    modification/derivatives thereof is transferred to you under Terms.
//
// 2. You understand that MStar Software might include, incorporate or be
//    supplied together with third party`s software and the use of MStar
//    Software may require additional licenses from third parties.  
//    Therefore, you hereby agree it is your sole responsibility to separately
//    obtain any and all third party right and license necessary for your use of
//    such third party`s software. 
//
// 3. MStar Software and any modification/derivatives thereof shall be deemed as
//    MStar`s confidential information and you agree to keep MStar`s 
//    confidential information in strictest confidence and not disclose to any
//    third party.  
//
// 4. MStar Software is provided on an "AS IS" basis without warranties of any
//    kind. Any warranties are hereby expressly disclaimed by MStar, including
//    without limitation, any warranties of merchantability, non-infringement of
//    intellectual property rights, fitness for a particular purpose, error free
//    and in conformity with any international standard.  You agree to waive any
//    claim against MStar for any loss, damage, cost or expense that you may
//    incur related to your use of MStar Software.
//    In no event shall MStar be liable for any direct, indirect, incidental or
//    consequential damages, including without limitation, lost of profit or
//    revenues, lost or damage of data, and unauthorized system use.
//    You agree that this Section 4 shall still apply without being affected
//    even if MStar Software has been modified by MStar in accordance with your
//    request or instruction for your use, except otherwise agreed by both
//    parties in writing.
//
// 5. If requested, MStar may from time to time provide technical supports or
//    services in relation with MStar Software to you for your use of
//    MStar Software in conjunction with your or your customer`s product
//    ("Services").
//    You understand and agree that, except otherwise agreed by both parties in
//    writing, Services are provided on an "AS IS" basis and the warranty
//    disclaimer set forth in Section 4 above shall apply.  
//
// 6. Nothing contained herein shall be construed as by implication, estoppels
//    or otherwise:
//    (a) conferring any license or right to use MStar name, trademark, service
//        mark, symbol or any other identification;
//    (b) obligating MStar or any of its affiliates to furnish any person,
//        including without limitation, you and your customers, any assistance
//        of any kind whatsoever, or any information; or 
//    (c) conferring any license or right under any intellectual property right.
//
// 7. These terms shall be governed by and construed in accordance with the laws
//    of Taiwan, R.O.C., excluding its conflict of law rules.
//    Any and all dispute arising out hereof or related hereto shall be finally
//    settled by arbitration referred to the Chinese Arbitration Association,
//    Taipei in accordance with the ROC Arbitration Law and the Arbitration
//    Rules of the Association by three (3) arbitrators appointed in accordance
//    with the said Rules.
//    The place of arbitration shall be in Taipei, Taiwan and the language shall
//    be English.  
//    The arbitration award shall be final and binding to both parties.
//
//******************************************************************************
//<MStar Software>

// This file is generated by script file, please do not edit it directly 
#ifndef _MSD8362MX_H_
#define _MSD8362MX_H_

#define PAD_NC   9999
#define PAD_GND  0

#define BALL_E9 PAD_GPIO_PM0
#define PAD_GPIO_PM0 9
#define GPIO_PAD_9 GPIO8
#ifndef BALL_E9_IS_GPIO
#define BALL_E9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM0_IS_GPIO
#define PAD_GPIO_PM0_IS_GPIO BALL_E9_IS_GPIO
#endif 

#define BALL_F9 PAD_GPIO_PM1
#define PAD_GPIO_PM1 10
#define GPIO_PAD_10 GPIO9
#ifndef BALL_F9_IS_GPIO
#define BALL_F9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM1_IS_GPIO
#define PAD_GPIO_PM1_IS_GPIO BALL_F9_IS_GPIO
#endif 

#define BALL_G9 PAD_GPIO_PM2
#define PAD_GPIO_PM2 11
#define GPIO_PAD_11 GPIO10
#ifndef BALL_G9_IS_GPIO
#define BALL_G9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM2_IS_GPIO
#define PAD_GPIO_PM2_IS_GPIO BALL_G9_IS_GPIO
#endif 

#define BALL_E8 PAD_GPIO_PM3
#define PAD_GPIO_PM3 12
#define GPIO_PAD_12 GPIO11
#ifndef BALL_E8_IS_GPIO
#define BALL_E8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM3_IS_GPIO
#define PAD_GPIO_PM3_IS_GPIO BALL_E8_IS_GPIO
#endif 

#define BALL_F8 PAD_GPIO_PM4
#define PAD_GPIO_PM4 13
#define GPIO_PAD_13 GPIO12
#ifndef BALL_F8_IS_GPIO
#define BALL_F8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM4_IS_GPIO
#define PAD_GPIO_PM4_IS_GPIO BALL_F8_IS_GPIO
#endif 

#define BALL_C8 PAD_PM_SPI_DI
#define PAD_PM_SPI_DI 3
#define GPIO_PAD_3 GPIO2
#ifndef BALL_C8_IS_GPIO
#define BALL_C8_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DI_IS_GPIO
#define PAD_PM_SPI_DI_IS_GPIO BALL_C8_IS_GPIO
#endif 

#define BALL_B9 PAD_PM_SPI_CZ
#define PAD_PM_SPI_CZ 1
#define GPIO_PAD_1 GPIO0
#ifndef BALL_B9_IS_GPIO
#define BALL_B9_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CZ_IS_GPIO
#define PAD_PM_SPI_CZ_IS_GPIO BALL_B9_IS_GPIO
#endif 

#define BALL_A7 PAD_PM_SPI_DO
#define PAD_PM_SPI_DO 4
#define GPIO_PAD_4 GPIO3
#ifndef BALL_A7_IS_GPIO
#define BALL_A7_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_DO_IS_GPIO
#define PAD_PM_SPI_DO_IS_GPIO BALL_A7_IS_GPIO
#endif 

#define BALL_B8 PAD_PM_SPI_CK
#define PAD_PM_SPI_CK 2
#define GPIO_PAD_2 GPIO1
#ifndef BALL_B8_IS_GPIO
#define BALL_B8_IS_GPIO 0
#endif 
#ifndef PAD_PM_SPI_CK_IS_GPIO
#define PAD_PM_SPI_CK_IS_GPIO BALL_B8_IS_GPIO
#endif 

#define BALL_A6 PAD_DDCA_CK
#define PAD_DDCA_CK 32
#define GPIO_PAD_32 GPIO31
#ifndef BALL_A6_IS_GPIO
#define BALL_A6_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_CK_IS_GPIO
#define PAD_DDCA_CK_IS_GPIO BALL_A6_IS_GPIO
#endif 

#define BALL_C7 PAD_DDCA_DA
#define PAD_DDCA_DA 33
#define GPIO_PAD_33 GPIO32
#ifndef BALL_C7_IS_GPIO
#define BALL_C7_IS_GPIO 0
#endif 
#ifndef PAD_DDCA_DA_IS_GPIO
#define PAD_DDCA_DA_IS_GPIO BALL_C7_IS_GPIO
#endif 

#define BALL_D8 PAD_GPIO_PM10
#define PAD_GPIO_PM10 19
#define GPIO_PAD_19 GPIO18
#ifndef BALL_D8_IS_GPIO
#define BALL_D8_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM10_IS_GPIO
#define PAD_GPIO_PM10_IS_GPIO BALL_D8_IS_GPIO
#endif 

#define BALL_C6 PAD_GPIO_PM11
#define PAD_GPIO_PM11 20
#define GPIO_PAD_20 GPIO19
#ifndef BALL_C6_IS_GPIO
#define BALL_C6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM11_IS_GPIO
#define PAD_GPIO_PM11_IS_GPIO BALL_C6_IS_GPIO
#endif 

#define BALL_B6 PAD_GPIO_PM12
#define PAD_GPIO_PM12 21
#define GPIO_PAD_21 GPIO20
#ifndef BALL_B6_IS_GPIO
#define BALL_B6_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM12_IS_GPIO
#define PAD_GPIO_PM12_IS_GPIO BALL_B6_IS_GPIO
#endif 

#define BALL_A2 PAD_GPIO_PM13
#define PAD_GPIO_PM13 22
#define GPIO_PAD_22 GPIO21
#ifndef BALL_A2_IS_GPIO
#define BALL_A2_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM13_IS_GPIO
#define PAD_GPIO_PM13_IS_GPIO BALL_A2_IS_GPIO
#endif 

#define BALL_B1 PAD_GPIO_PM14
#define PAD_GPIO_PM14 23
#define GPIO_PAD_23 GPIO22
#ifndef BALL_B1_IS_GPIO
#define BALL_B1_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM14_IS_GPIO
#define PAD_GPIO_PM14_IS_GPIO BALL_B1_IS_GPIO
#endif 

#define BALL_A4 PAD_GPIO_PM15
#define PAD_GPIO_PM15 24
#define GPIO_PAD_24 GPIO23
#ifndef BALL_A4_IS_GPIO
#define BALL_A4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM15_IS_GPIO
#define PAD_GPIO_PM15_IS_GPIO BALL_A4_IS_GPIO
#endif 

#define BALL_B5 PAD_GPIO_PM16
#define PAD_GPIO_PM16 25
#define GPIO_PAD_25 GPIO24
#ifndef BALL_B5_IS_GPIO
#define BALL_B5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM16_IS_GPIO
#define PAD_GPIO_PM16_IS_GPIO BALL_B5_IS_GPIO
#endif 

#define BALL_B4 PAD_GPIO_PM17
#define PAD_GPIO_PM17 26
#define GPIO_PAD_26 GPIO25
#ifndef BALL_B4_IS_GPIO
#define BALL_B4_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM17_IS_GPIO
#define PAD_GPIO_PM17_IS_GPIO BALL_B4_IS_GPIO
#endif 

#define BALL_C5 PAD_GPIO_PM18
#define PAD_GPIO_PM18 27
#define GPIO_PAD_27 GPIO26
#ifndef BALL_C5_IS_GPIO
#define BALL_C5_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM18_IS_GPIO
#define PAD_GPIO_PM18_IS_GPIO BALL_C5_IS_GPIO
#endif 

#define BALL_C4 PAD_IRIN
#define PAD_IRIN 5
#define GPIO_PAD_5 GPIO4
#ifndef BALL_C4_IS_GPIO
#define BALL_C4_IS_GPIO 0
#endif 
#ifndef PAD_IRIN_IS_GPIO
#define PAD_IRIN_IS_GPIO BALL_C4_IS_GPIO
#endif 

#define PAD_AV_LNK 9999
#ifndef PAD_AV_LNK_IS_GPIO
#define PAD_AV_LNK_IS_GPIO 0
#endif 

#define BALL_A3 PAD_PWM_PM
#define PAD_PWM_PM 8
#define GPIO_PAD_8 GPIO7
#ifndef BALL_A3_IS_GPIO
#define BALL_A3_IS_GPIO 0
#endif 
#ifndef PAD_PWM_PM_IS_GPIO
#define PAD_PWM_PM_IS_GPIO BALL_A3_IS_GPIO
#endif 

#define BALL_B2 PAD_HOTPLUGA
#define PAD_HOTPLUGA 28
#define GPIO_PAD_28 GPIO27
#ifndef BALL_B2_IS_GPIO
#define BALL_B2_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGA_IS_GPIO
#define PAD_HOTPLUGA_IS_GPIO BALL_B2_IS_GPIO
#endif 

#define BALL_C2 PAD_DDCDA_CK
#define PAD_DDCDA_CK 34
#define GPIO_PAD_34 GPIO33
#ifndef BALL_C2_IS_GPIO
#define BALL_C2_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_CK_IS_GPIO
#define PAD_DDCDA_CK_IS_GPIO BALL_C2_IS_GPIO
#endif 

#define BALL_C3 PAD_DDCDA_DA
#define PAD_DDCDA_DA 35
#define GPIO_PAD_35 GPIO34
#ifndef BALL_C3_IS_GPIO
#define BALL_C3_IS_GPIO 0
#endif 
#ifndef PAD_DDCDA_DA_IS_GPIO
#define PAD_DDCDA_DA_IS_GPIO BALL_C3_IS_GPIO
#endif 

#define BALL_D2 PAD_DDCDB_CK
#define PAD_DDCDB_CK 36
#define GPIO_PAD_36 GPIO35
#ifndef BALL_D2_IS_GPIO
#define BALL_D2_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_CK_IS_GPIO
#define PAD_DDCDB_CK_IS_GPIO BALL_D2_IS_GPIO
#endif 

#define BALL_D1 PAD_DDCDB_DA
#define PAD_DDCDB_DA 37
#define GPIO_PAD_37 GPIO36
#ifndef BALL_D1_IS_GPIO
#define BALL_D1_IS_GPIO 0
#endif 
#ifndef PAD_DDCDB_DA_IS_GPIO
#define PAD_DDCDB_DA_IS_GPIO BALL_D1_IS_GPIO
#endif 

#define BALL_D3 PAD_HOTPLUGB
#define PAD_HOTPLUGB 29
#define GPIO_PAD_29 GPIO28
#ifndef BALL_D3_IS_GPIO
#define BALL_D3_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGB_IS_GPIO
#define PAD_HOTPLUGB_IS_GPIO BALL_D3_IS_GPIO
#endif 

#define PAD_DDCDC_DA 9999
#ifndef PAD_DDCDC_DA_IS_GPIO
#define PAD_DDCDC_DA_IS_GPIO 0
#endif 

#define BALL_E4 PAD_DDCDD_CK
#define PAD_DDCDD_CK 40
#define GPIO_PAD_40 GPIO39
#ifndef BALL_E4_IS_GPIO
#define BALL_E4_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_CK_IS_GPIO
#define PAD_DDCDD_CK_IS_GPIO BALL_E4_IS_GPIO
#endif 

#define BALL_E5 PAD_DDCDD_DA
#define PAD_DDCDD_DA 41
#define GPIO_PAD_41 GPIO40
#ifndef BALL_E5_IS_GPIO
#define BALL_E5_IS_GPIO 0
#endif 
#ifndef PAD_DDCDD_DA_IS_GPIO
#define PAD_DDCDD_DA_IS_GPIO BALL_E5_IS_GPIO
#endif 

#define BALL_D5 PAD_CEC
#define PAD_CEC 6
#define GPIO_PAD_6 GPIO5
#ifndef BALL_D5_IS_GPIO
#define BALL_D5_IS_GPIO 0
#endif 
#ifndef PAD_CEC_IS_GPIO
#define PAD_CEC_IS_GPIO BALL_D5_IS_GPIO
#endif 

#define PAD_DDCDC_CK 9999
#ifndef PAD_DDCDC_CK_IS_GPIO
#define PAD_DDCDC_CK_IS_GPIO 0
#endif 

#define PAD_HOTPLUGC 9999
#ifndef PAD_HOTPLUGC_IS_GPIO
#define PAD_HOTPLUGC_IS_GPIO 0
#endif 

#define BALL_D4 PAD_HOTPLUGD
#define PAD_HOTPLUGD 31
#define GPIO_PAD_31 GPIO30
#ifndef BALL_D4_IS_GPIO
#define BALL_D4_IS_GPIO 0
#endif 
#ifndef PAD_HOTPLUGD_IS_GPIO
#define PAD_HOTPLUGD_IS_GPIO BALL_D4_IS_GPIO
#endif 

#define BALL_Y3 PAD_PCM_A14
#define PAD_PCM_A14 127
#define GPIO_PAD_127 GPIO126
#ifndef BALL_Y3_IS_GPIO
#define BALL_Y3_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A14_IS_GPIO
#define PAD_PCM_A14_IS_GPIO BALL_Y3_IS_GPIO
#endif 

#define BALL_Y1 PAD_PCM_A13
#define PAD_PCM_A13 126
#define GPIO_PAD_126 GPIO125
#ifndef BALL_Y1_IS_GPIO
#define BALL_Y1_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A13_IS_GPIO
#define PAD_PCM_A13_IS_GPIO BALL_Y1_IS_GPIO
#endif 

#define BALL_AB6 PAD_PCM_A3
#define PAD_PCM_A3 136
#define GPIO_PAD_136 GPIO135
#ifndef BALL_AB6_IS_GPIO
#define BALL_AB6_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A3_IS_GPIO
#define PAD_PCM_A3_IS_GPIO BALL_AB6_IS_GPIO
#endif 

#define BALL_AB2 PAD_TGPIO0
#define PAD_TGPIO0 178
#define GPIO_PAD_178 GPIO177
#ifndef BALL_AB2_IS_GPIO
#define BALL_AB2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO0_IS_GPIO
#define PAD_TGPIO0_IS_GPIO BALL_AB2_IS_GPIO
#endif 

#define BALL_AA7 PAD_PCM_A2
#define PAD_PCM_A2 137
#define GPIO_PAD_137 GPIO136
#ifndef BALL_AA7_IS_GPIO
#define BALL_AA7_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A2_IS_GPIO
#define PAD_PCM_A2_IS_GPIO BALL_AA7_IS_GPIO
#endif 

#define BALL_AB1 PAD_TGPIO1
#define PAD_TGPIO1 179
#define GPIO_PAD_179 GPIO178
#ifndef BALL_AB1_IS_GPIO
#define BALL_AB1_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO1_IS_GPIO
#define PAD_TGPIO1_IS_GPIO BALL_AB1_IS_GPIO
#endif 

#define BALL_AA6 PAD_PCM_A4
#define PAD_PCM_A4 135
#define GPIO_PAD_135 GPIO134
#ifndef BALL_AA6_IS_GPIO
#define BALL_AA6_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A4_IS_GPIO
#define PAD_PCM_A4_IS_GPIO BALL_AA6_IS_GPIO
#endif 

#define BALL_V2 PAD_TGPIO2
#define PAD_TGPIO2 180
#define GPIO_PAD_180 GPIO179
#ifndef BALL_V2_IS_GPIO
#define BALL_V2_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO2_IS_GPIO
#define PAD_TGPIO2_IS_GPIO BALL_V2_IS_GPIO
#endif 

#define BALL_AB4 PAD_PCM_A7
#define PAD_PCM_A7 131
#define GPIO_PAD_131 GPIO130
#ifndef BALL_AB4_IS_GPIO
#define BALL_AB4_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A7_IS_GPIO
#define PAD_PCM_A7_IS_GPIO BALL_AB4_IS_GPIO
#endif 

#define BALL_V3 PAD_TGPIO3
#define PAD_TGPIO3 181
#define GPIO_PAD_181 GPIO180
#ifndef BALL_V3_IS_GPIO
#define BALL_V3_IS_GPIO 0
#endif 
#ifndef PAD_TGPIO3_IS_GPIO
#define PAD_TGPIO3_IS_GPIO BALL_V3_IS_GPIO
#endif 

#define BALL_AA5 PAD_PCM_A6
#define PAD_PCM_A6 132
#define GPIO_PAD_132 GPIO131
#ifndef BALL_AA5_IS_GPIO
#define BALL_AA5_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A6_IS_GPIO
#define PAD_PCM_A6_IS_GPIO BALL_AA5_IS_GPIO
#endif 

#define BALL_U7 PAD_TS0_D0
#define PAD_TS0_D0 182
#define GPIO_PAD_182 GPIO181
#ifndef BALL_U7_IS_GPIO
#define BALL_U7_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D0_IS_GPIO
#define PAD_TS0_D0_IS_GPIO BALL_U7_IS_GPIO
#endif 

#define BALL_AB5 PAD_PCM_A5
#define PAD_PCM_A5 133
#define GPIO_PAD_133 GPIO132
#ifndef BALL_AB5_IS_GPIO
#define BALL_AB5_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A5_IS_GPIO
#define PAD_PCM_A5_IS_GPIO BALL_AB5_IS_GPIO
#endif 

#define BALL_U12 PAD_TS0_D1
#define PAD_TS0_D1 183
#define GPIO_PAD_183 GPIO182
#ifndef BALL_U12_IS_GPIO
#define BALL_U12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D1_IS_GPIO
#define PAD_TS0_D1_IS_GPIO BALL_U12_IS_GPIO
#endif 

#define BALL_T11 PAD_TS0_D2
#define PAD_TS0_D2 184
#define GPIO_PAD_184 GPIO183
#ifndef BALL_T11_IS_GPIO
#define BALL_T11_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D2_IS_GPIO
#define PAD_TS0_D2_IS_GPIO BALL_T11_IS_GPIO
#endif 

#define BALL_V11 PAD_PCM_A12
#define PAD_PCM_A12 130
#define GPIO_PAD_130 GPIO129
#ifndef BALL_V11_IS_GPIO
#define BALL_V11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A12_IS_GPIO
#define PAD_PCM_A12_IS_GPIO BALL_V11_IS_GPIO
#endif 

#define BALL_U11 PAD_TS0_D3
#define PAD_TS0_D3 185
#define GPIO_PAD_185 GPIO184
#ifndef BALL_U11_IS_GPIO
#define BALL_U11_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D3_IS_GPIO
#define PAD_TS0_D3_IS_GPIO BALL_U11_IS_GPIO
#endif 

#define PAD_PCM_IORD_N 9999
#ifndef PAD_PCM_IORD_N_IS_GPIO
#define PAD_PCM_IORD_N_IS_GPIO 0
#endif 

#define BALL_R12 PAD_TS0_D4
#define PAD_TS0_D4 186
#define GPIO_PAD_186 GPIO185
#ifndef BALL_R12_IS_GPIO
#define BALL_R12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D4_IS_GPIO
#define PAD_TS0_D4_IS_GPIO BALL_R12_IS_GPIO
#endif 

#define BALL_W11 PAD_PCM_A9
#define PAD_PCM_A9 123
#define GPIO_PAD_123 GPIO122
#ifndef BALL_W11_IS_GPIO
#define BALL_W11_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A9_IS_GPIO
#define PAD_PCM_A9_IS_GPIO BALL_W11_IS_GPIO
#endif 

#define BALL_V12 PAD_TS0_D5
#define PAD_TS0_D5 187
#define GPIO_PAD_187 GPIO186
#ifndef BALL_V12_IS_GPIO
#define BALL_V12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D5_IS_GPIO
#define PAD_TS0_D5_IS_GPIO BALL_V12_IS_GPIO
#endif 

#define BALL_AB7 PAD_PCM_A1
#define PAD_PCM_A1 139
#define GPIO_PAD_139 GPIO138
#ifndef BALL_AB7_IS_GPIO
#define BALL_AB7_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A1_IS_GPIO
#define PAD_PCM_A1_IS_GPIO BALL_AB7_IS_GPIO
#endif 

#define BALL_T12 PAD_TS0_D6
#define PAD_TS0_D6 188
#define GPIO_PAD_188 GPIO187
#ifndef BALL_T12_IS_GPIO
#define BALL_T12_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D6_IS_GPIO
#define PAD_TS0_D6_IS_GPIO BALL_T12_IS_GPIO
#endif 

#define BALL_Y7 PAD_PCM_A0
#define PAD_PCM_A0 140
#define GPIO_PAD_140 GPIO139
#ifndef BALL_Y7_IS_GPIO
#define BALL_Y7_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A0_IS_GPIO
#define PAD_PCM_A0_IS_GPIO BALL_Y7_IS_GPIO
#endif 

#define BALL_T13 PAD_TS0_D7
#define PAD_TS0_D7 189
#define GPIO_PAD_189 GPIO188
#ifndef BALL_T13_IS_GPIO
#define BALL_T13_IS_GPIO 0
#endif 
#ifndef PAD_TS0_D7_IS_GPIO
#define PAD_TS0_D7_IS_GPIO BALL_T13_IS_GPIO
#endif 

#define BALL_W12 PAD_PCM_D0
#define PAD_PCM_D0 141
#define GPIO_PAD_141 GPIO140
#ifndef BALL_W12_IS_GPIO
#define BALL_W12_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D0_IS_GPIO
#define PAD_PCM_D0_IS_GPIO BALL_W12_IS_GPIO
#endif 

#define BALL_U5 PAD_TS0_VLD
#define PAD_TS0_VLD 190
#define GPIO_PAD_190 GPIO189
#ifndef BALL_U5_IS_GPIO
#define BALL_U5_IS_GPIO 0
#endif 
#ifndef PAD_TS0_VLD_IS_GPIO
#define PAD_TS0_VLD_IS_GPIO BALL_U5_IS_GPIO
#endif 

#define BALL_T14 PAD_PCM_D1
#define PAD_PCM_D1 142
#define GPIO_PAD_142 GPIO141
#ifndef BALL_T14_IS_GPIO
#define BALL_T14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D1_IS_GPIO
#define PAD_PCM_D1_IS_GPIO BALL_T14_IS_GPIO
#endif 

#define BALL_U6 PAD_TS0_SYNC
#define PAD_TS0_SYNC 191
#define GPIO_PAD_191 GPIO190
#ifndef BALL_U6_IS_GPIO
#define BALL_U6_IS_GPIO 0
#endif 
#ifndef PAD_TS0_SYNC_IS_GPIO
#define PAD_TS0_SYNC_IS_GPIO BALL_U6_IS_GPIO
#endif 

#define BALL_U14 PAD_PCM_D2
#define PAD_PCM_D2 143
#define GPIO_PAD_143 GPIO142
#ifndef BALL_U14_IS_GPIO
#define BALL_U14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D2_IS_GPIO
#define PAD_PCM_D2_IS_GPIO BALL_U14_IS_GPIO
#endif 

#define BALL_U4 PAD_TS0_CLK
#define PAD_TS0_CLK 192
#define GPIO_PAD_192 GPIO191
#ifndef BALL_U4_IS_GPIO
#define BALL_U4_IS_GPIO 0
#endif 
#ifndef PAD_TS0_CLK_IS_GPIO
#define PAD_TS0_CLK_IS_GPIO BALL_U4_IS_GPIO
#endif 

#define BALL_U13 PAD_PCM_D3
#define PAD_PCM_D3 113
#define GPIO_PAD_113 GPIO112
#ifndef BALL_U13_IS_GPIO
#define BALL_U13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D3_IS_GPIO
#define PAD_PCM_D3_IS_GPIO BALL_U13_IS_GPIO
#endif 

#define BALL_V4 PAD_TS1_CLK
#define PAD_TS1_CLK 193
#define GPIO_PAD_193 GPIO192
#ifndef BALL_V4_IS_GPIO
#define BALL_V4_IS_GPIO 0
#endif 
#ifndef PAD_TS1_CLK_IS_GPIO
#define PAD_TS1_CLK_IS_GPIO BALL_V4_IS_GPIO
#endif 

#define BALL_V13 PAD_PCM_A8
#define PAD_PCM_A8 125
#define GPIO_PAD_125 GPIO124
#ifndef BALL_V13_IS_GPIO
#define BALL_V13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A8_IS_GPIO
#define PAD_PCM_A8_IS_GPIO BALL_V13_IS_GPIO
#endif 

#define BALL_V5 PAD_TS1_SYNC
#define PAD_TS1_SYNC 194
#define GPIO_PAD_194 GPIO193
#ifndef BALL_V5_IS_GPIO
#define BALL_V5_IS_GPIO 0
#endif 
#ifndef PAD_TS1_SYNC_IS_GPIO
#define PAD_TS1_SYNC_IS_GPIO BALL_V5_IS_GPIO
#endif 

#define BALL_V6 PAD_TS1_VLD
#define PAD_TS1_VLD 195
#define GPIO_PAD_195 GPIO194
#ifndef BALL_V6_IS_GPIO
#define BALL_V6_IS_GPIO 0
#endif 
#ifndef PAD_TS1_VLD_IS_GPIO
#define PAD_TS1_VLD_IS_GPIO BALL_V6_IS_GPIO
#endif 

#define BALL_Y8 PAD_TS1_D7
#define PAD_TS1_D7 196
#define GPIO_PAD_196 GPIO195
#ifndef BALL_Y8_IS_GPIO
#define BALL_Y8_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D7_IS_GPIO
#define PAD_TS1_D7_IS_GPIO BALL_Y8_IS_GPIO
#endif 

#define BALL_Y5 PAD_TS1_D6
#define PAD_TS1_D6 197
#define GPIO_PAD_197 GPIO196
#ifndef BALL_Y5_IS_GPIO
#define BALL_Y5_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D6_IS_GPIO
#define PAD_TS1_D6_IS_GPIO BALL_Y5_IS_GPIO
#endif 

#define BALL_W5 PAD_TS1_D5
#define PAD_TS1_D5 198
#define GPIO_PAD_198 GPIO197
#ifndef BALL_W5_IS_GPIO
#define BALL_W5_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D5_IS_GPIO
#define PAD_TS1_D5_IS_GPIO BALL_W5_IS_GPIO
#endif 

#define BALL_W6 PAD_TS1_D4
#define PAD_TS1_D4 199
#define GPIO_PAD_199 GPIO198
#ifndef BALL_W6_IS_GPIO
#define BALL_W6_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D4_IS_GPIO
#define PAD_TS1_D4_IS_GPIO BALL_W6_IS_GPIO
#endif 

#define BALL_AE3 PAD_NAND_DQS
#define PAD_NAND_DQS 107
#define GPIO_PAD_107 GPIO106
#ifndef BALL_AE3_IS_GPIO
#define BALL_AE3_IS_GPIO 0
#endif 
#ifndef PAD_NAND_DQS_IS_GPIO
#define PAD_NAND_DQS_IS_GPIO BALL_AE3_IS_GPIO
#endif 

#define BALL_Y6 PAD_TS1_D3
#define PAD_TS1_D3 200
#define GPIO_PAD_200 GPIO199
#ifndef BALL_Y6_IS_GPIO
#define BALL_Y6_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D3_IS_GPIO
#define PAD_TS1_D3_IS_GPIO BALL_Y6_IS_GPIO
#endif 

#define BALL_AC4 PAD_EMMC_RSTN
#define PAD_EMMC_RSTN 159
#define GPIO_PAD_159 GPIO158
#ifndef BALL_AC4_IS_GPIO
#define BALL_AC4_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_RSTN_IS_GPIO
#define PAD_EMMC_RSTN_IS_GPIO BALL_AC4_IS_GPIO
#endif 

#define BALL_AA4 PAD_TS1_D2
#define PAD_TS1_D2 201
#define GPIO_PAD_201 GPIO200
#ifndef BALL_AA4_IS_GPIO
#define BALL_AA4_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D2_IS_GPIO
#define PAD_TS1_D2_IS_GPIO BALL_AA4_IS_GPIO
#endif 

#define BALL_AC3 PAD_EMMC_CMD
#define PAD_EMMC_CMD 161
#define GPIO_PAD_161 GPIO160
#ifndef BALL_AC3_IS_GPIO
#define BALL_AC3_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_CMD_IS_GPIO
#define PAD_EMMC_CMD_IS_GPIO BALL_AC3_IS_GPIO
#endif 

#define BALL_W7 PAD_TS1_D1
#define PAD_TS1_D1 202
#define GPIO_PAD_202 GPIO201
#ifndef BALL_W7_IS_GPIO
#define BALL_W7_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D1_IS_GPIO
#define PAD_TS1_D1_IS_GPIO BALL_W7_IS_GPIO
#endif 

#define BALL_AD4 PAD_EMMC_CLK
#define PAD_EMMC_CLK 160
#define GPIO_PAD_160 GPIO159
#ifndef BALL_AD4_IS_GPIO
#define BALL_AD4_IS_GPIO 0
#endif 
#ifndef PAD_EMMC_CLK_IS_GPIO
#define PAD_EMMC_CLK_IS_GPIO BALL_AD4_IS_GPIO
#endif 

#define BALL_V7 PAD_TS1_D0
#define PAD_TS1_D0 203
#define GPIO_PAD_203 GPIO202
#ifndef BALL_V7_IS_GPIO
#define BALL_V7_IS_GPIO 0
#endif 
#ifndef PAD_TS1_D0_IS_GPIO
#define PAD_TS1_D0_IS_GPIO BALL_V7_IS_GPIO
#endif 

#define BALL_AC7 PAD_NAND_CEZ1
#define PAD_NAND_CEZ1 100
#define GPIO_PAD_100 GPIO99
#ifndef BALL_AC7_IS_GPIO
#define BALL_AC7_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ1_IS_GPIO
#define PAD_NAND_CEZ1_IS_GPIO BALL_AC7_IS_GPIO
#endif 

#define PAD_PCM_WE_N 9999
#ifndef PAD_PCM_WE_N_IS_GPIO
#define PAD_PCM_WE_N_IS_GPIO 0
#endif 

#define BALL_AC6 PAD_NAND_CEZ
#define PAD_NAND_CEZ 99
#define GPIO_PAD_99 GPIO98
#ifndef BALL_AC6_IS_GPIO
#define BALL_AC6_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CEZ_IS_GPIO
#define PAD_NAND_CEZ_IS_GPIO BALL_AC6_IS_GPIO
#endif 

#define PAD_PCM_REG_N 9999
#ifndef PAD_PCM_REG_N_IS_GPIO
#define PAD_PCM_REG_N_IS_GPIO 0
#endif 

#define PAD_PCM_IOWR_N 9999
#ifndef PAD_PCM_IOWR_N_IS_GPIO
#define PAD_PCM_IOWR_N_IS_GPIO 0
#endif 

#define BALL_AE6 PAD_NAND_CLE
#define PAD_NAND_CLE 101
#define GPIO_PAD_101 GPIO100
#ifndef BALL_AE6_IS_GPIO
#define BALL_AE6_IS_GPIO 0
#endif 
#ifndef PAD_NAND_CLE_IS_GPIO
#define PAD_NAND_CLE_IS_GPIO BALL_AE6_IS_GPIO
#endif 

#define BALL_AD5 PAD_NAND_REZ
#define PAD_NAND_REZ 102
#define GPIO_PAD_102 GPIO101
#ifndef BALL_AD5_IS_GPIO
#define BALL_AD5_IS_GPIO 0
#endif 
#ifndef PAD_NAND_REZ_IS_GPIO
#define PAD_NAND_REZ_IS_GPIO BALL_AD5_IS_GPIO
#endif 

#define PAD_PCM_IRQA_N 9999
#ifndef PAD_PCM_IRQA_N_IS_GPIO
#define PAD_PCM_IRQA_N_IS_GPIO 0
#endif 

#define PAD_PCM_WAIT_N 9999
#ifndef PAD_PCM_WAIT_N_IS_GPIO
#define PAD_PCM_WAIT_N_IS_GPIO 0
#endif 

#define BALL_AE5 PAD_NAND_WEZ
#define PAD_NAND_WEZ 103
#define GPIO_PAD_103 GPIO102
#ifndef BALL_AE5_IS_GPIO
#define BALL_AE5_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WEZ_IS_GPIO
#define PAD_NAND_WEZ_IS_GPIO BALL_AE5_IS_GPIO
#endif 

#define PAD_PCM_CD_N 9999
#ifndef PAD_PCM_CD_N_IS_GPIO
#define PAD_PCM_CD_N_IS_GPIO 0
#endif 

#define BALL_AC5 PAD_NAND_RBZ
#define PAD_NAND_RBZ 106
#define GPIO_PAD_106 GPIO105
#ifndef BALL_AC5_IS_GPIO
#define BALL_AC5_IS_GPIO 0
#endif 
#ifndef PAD_NAND_RBZ_IS_GPIO
#define PAD_NAND_RBZ_IS_GPIO BALL_AC5_IS_GPIO
#endif 

#define PAD_PCM_RESET 9999
#ifndef PAD_PCM_RESET_IS_GPIO
#define PAD_PCM_RESET_IS_GPIO 0
#endif 

#define BALL_AD7 PAD_NAND_WPZ
#define PAD_NAND_WPZ 104
#define GPIO_PAD_104 GPIO103
#ifndef BALL_AD7_IS_GPIO
#define BALL_AD7_IS_GPIO 0
#endif 
#ifndef PAD_NAND_WPZ_IS_GPIO
#define PAD_NAND_WPZ_IS_GPIO BALL_AD7_IS_GPIO
#endif 

#define BALL_R14 PAD_PCM_A11
#define PAD_PCM_A11 121
#define GPIO_PAD_121 GPIO120
#ifndef BALL_R14_IS_GPIO
#define BALL_R14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A11_IS_GPIO
#define PAD_PCM_A11_IS_GPIO BALL_R14_IS_GPIO
#endif 

#define BALL_AD6 PAD_NAND_ALE
#define PAD_NAND_ALE 105
#define GPIO_PAD_105 GPIO104
#ifndef BALL_AD6_IS_GPIO
#define BALL_AD6_IS_GPIO 0
#endif 
#ifndef PAD_NAND_ALE_IS_GPIO
#define PAD_NAND_ALE_IS_GPIO BALL_AD6_IS_GPIO
#endif 

#define BALL_R13 PAD_PCM_D6
#define PAD_PCM_D6 116
#define GPIO_PAD_116 GPIO115
#ifndef BALL_R13_IS_GPIO
#define BALL_R13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D6_IS_GPIO
#define PAD_PCM_D6_IS_GPIO BALL_R13_IS_GPIO
#endif 

#define PAD_PCM_CE_N 9999
#ifndef PAD_PCM_CE_N_IS_GPIO
#define PAD_PCM_CE_N_IS_GPIO 0
#endif 

#define BALL_W13 PAD_PCM_D7
#define PAD_PCM_D7 117
#define GPIO_PAD_117 GPIO116
#ifndef BALL_W13_IS_GPIO
#define BALL_W13_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D7_IS_GPIO
#define PAD_PCM_D7_IS_GPIO BALL_W13_IS_GPIO
#endif 

#define BALL_R15 PAD_PCM_A10
#define PAD_PCM_A10 119
#define GPIO_PAD_119 GPIO118
#ifndef BALL_R15_IS_GPIO
#define BALL_R15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_A10_IS_GPIO
#define PAD_PCM_A10_IS_GPIO BALL_R15_IS_GPIO
#endif 

#define PAD_PCM_OE_N 9999
#ifndef PAD_PCM_OE_N_IS_GPIO
#define PAD_PCM_OE_N_IS_GPIO 0
#endif 

#define BALL_T15 PAD_PCM_D4
#define PAD_PCM_D4 114
#define GPIO_PAD_114 GPIO113
#ifndef BALL_T15_IS_GPIO
#define BALL_T15_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D4_IS_GPIO
#define PAD_PCM_D4_IS_GPIO BALL_T15_IS_GPIO
#endif 

#define BALL_V14 PAD_PCM_D5
#define PAD_PCM_D5 115
#define GPIO_PAD_115 GPIO114
#ifndef BALL_V14_IS_GPIO
#define BALL_V14_IS_GPIO 0
#endif 
#ifndef PAD_PCM_D5_IS_GPIO
#define PAD_PCM_D5_IS_GPIO BALL_V14_IS_GPIO
#endif 

#define PAD_VSYNC_Like 9999
#ifndef PAD_VSYNC_Like_IS_GPIO
#define PAD_VSYNC_Like_IS_GPIO 0
#endif 

#define PAD_SPI1_DI 9999
#ifndef PAD_SPI1_DI_IS_GPIO
#define PAD_SPI1_DI_IS_GPIO 0
#endif 

#define PAD_SPI1_CK 9999
#ifndef PAD_SPI1_CK_IS_GPIO
#define PAD_SPI1_CK_IS_GPIO 0
#endif 

#define PAD_SPI2_DI 9999
#ifndef PAD_SPI2_DI_IS_GPIO
#define PAD_SPI2_DI_IS_GPIO 0
#endif 

#define PAD_SPI2_CK 9999
#ifndef PAD_SPI2_CK_IS_GPIO
#define PAD_SPI2_CK_IS_GPIO 0
#endif 

#define PAD_PCM2_CE_N 9999
#ifndef PAD_PCM2_CE_N_IS_GPIO
#define PAD_PCM2_CE_N_IS_GPIO 0
#endif 

#define PAD_PCM2_IRQA_N 9999
#ifndef PAD_PCM2_IRQA_N_IS_GPIO
#define PAD_PCM2_IRQA_N_IS_GPIO 0
#endif 

#define PAD_PCM2_WAIT_N 9999
#ifndef PAD_PCM2_WAIT_N_IS_GPIO
#define PAD_PCM2_WAIT_N_IS_GPIO 0
#endif 

#define PAD_PCM2_RESET 9999
#ifndef PAD_PCM2_RESET_IS_GPIO
#define PAD_PCM2_RESET_IS_GPIO 0
#endif 

#define PAD_PCM2_CD_N 9999
#ifndef PAD_PCM2_CD_N_IS_GPIO
#define PAD_PCM2_CD_N_IS_GPIO 0
#endif 

#define PAD_TS2_CLK 9999
#ifndef PAD_TS2_CLK_IS_GPIO
#define PAD_TS2_CLK_IS_GPIO 0
#endif 

#define PAD_TS2_SYNC 9999
#ifndef PAD_TS2_SYNC_IS_GPIO
#define PAD_TS2_SYNC_IS_GPIO 0
#endif 

#define PAD_TS2_VLD 9999
#ifndef PAD_TS2_VLD_IS_GPIO
#define PAD_TS2_VLD_IS_GPIO 0
#endif 

#define PAD_TS2_D0 9999
#ifndef PAD_TS2_D0_IS_GPIO
#define PAD_TS2_D0_IS_GPIO 0
#endif 

#define PAD_TS2_D1 9999
#ifndef PAD_TS2_D1_IS_GPIO
#define PAD_TS2_D1_IS_GPIO 0
#endif 

#define PAD_TS2_D2 9999
#ifndef PAD_TS2_D2_IS_GPIO
#define PAD_TS2_D2_IS_GPIO 0
#endif 

#define PAD_TS2_D3 9999
#ifndef PAD_TS2_D3_IS_GPIO
#define PAD_TS2_D3_IS_GPIO 0
#endif 

#define PAD_TS2_D4 9999
#ifndef PAD_TS2_D4_IS_GPIO
#define PAD_TS2_D4_IS_GPIO 0
#endif 

#define PAD_TS2_D5 9999
#ifndef PAD_TS2_D5_IS_GPIO
#define PAD_TS2_D5_IS_GPIO 0
#endif 

#define PAD_TS2_D6 9999
#ifndef PAD_TS2_D6_IS_GPIO
#define PAD_TS2_D6_IS_GPIO 0
#endif 

#define PAD_TS2_D7 9999
#ifndef PAD_TS2_D7_IS_GPIO
#define PAD_TS2_D7_IS_GPIO 0
#endif 

#define PAD_TCON0 9999
#ifndef PAD_TCON0_IS_GPIO
#define PAD_TCON0_IS_GPIO 0
#endif 

#define PAD_TCON1 9999
#ifndef PAD_TCON1_IS_GPIO
#define PAD_TCON1_IS_GPIO 0
#endif 

#define PAD_TCON2 9999
#ifndef PAD_TCON2_IS_GPIO
#define PAD_TCON2_IS_GPIO 0
#endif 

#define PAD_TCON3 9999
#ifndef PAD_TCON3_IS_GPIO
#define PAD_TCON3_IS_GPIO 0
#endif 

#define PAD_TCON4 9999
#ifndef PAD_TCON4_IS_GPIO
#define PAD_TCON4_IS_GPIO 0
#endif 

#define PAD_TCON5 9999
#ifndef PAD_TCON5_IS_GPIO
#define PAD_TCON5_IS_GPIO 0
#endif 

#define PAD_TCON6 9999
#ifndef PAD_TCON6_IS_GPIO
#define PAD_TCON6_IS_GPIO 0
#endif 

#define PAD_TCON7 9999
#ifndef PAD_TCON7_IS_GPIO
#define PAD_TCON7_IS_GPIO 0
#endif 

#define PAD_TCON8 9999
#ifndef PAD_TCON8_IS_GPIO
#define PAD_TCON8_IS_GPIO 0
#endif 

#define PAD_TCON9 9999
#ifndef PAD_TCON9_IS_GPIO
#define PAD_TCON9_IS_GPIO 0
#endif 

#define PAD_TCON10 9999
#ifndef PAD_TCON10_IS_GPIO
#define PAD_TCON10_IS_GPIO 0
#endif 

#define PAD_TCON15 9999
#ifndef PAD_TCON15_IS_GPIO
#define PAD_TCON15_IS_GPIO 0
#endif 

#define PAD_TCON11 9999
#ifndef PAD_TCON11_IS_GPIO
#define PAD_TCON11_IS_GPIO 0
#endif 

#define PAD_TCON12 9999
#ifndef PAD_TCON12_IS_GPIO
#define PAD_TCON12_IS_GPIO 0
#endif 

#define PAD_TCON13 9999
#ifndef PAD_TCON13_IS_GPIO
#define PAD_TCON13_IS_GPIO 0
#endif 

#define PAD_TCON14 9999
#ifndef PAD_TCON14_IS_GPIO
#define PAD_TCON14_IS_GPIO 0
#endif 

#define PAD_GPIO18 9999
#ifndef PAD_GPIO18_IS_GPIO
#define PAD_GPIO18_IS_GPIO 0
#endif 

#define PAD_GPIO19 9999
#ifndef PAD_GPIO19_IS_GPIO
#define PAD_GPIO19_IS_GPIO 0
#endif 

#define PAD_GPIO20 9999
#ifndef PAD_GPIO20_IS_GPIO
#define PAD_GPIO20_IS_GPIO 0
#endif 

#define PAD_GPIO21 9999
#ifndef PAD_GPIO21_IS_GPIO
#define PAD_GPIO21_IS_GPIO 0
#endif 

#define PAD_GPIO22 9999
#ifndef PAD_GPIO22_IS_GPIO
#define PAD_GPIO22_IS_GPIO 0
#endif 

#define PAD_GPIO25 9999
#ifndef PAD_GPIO25_IS_GPIO
#define PAD_GPIO25_IS_GPIO 0
#endif 

#define PAD_PWM8 9999
#ifndef PAD_PWM8_IS_GPIO
#define PAD_PWM8_IS_GPIO 0
#endif 

#define PAD_PWM9 9999
#ifndef PAD_PWM9_IS_GPIO
#define PAD_PWM9_IS_GPIO 0
#endif 

#define PAD_PWM10 9999
#ifndef PAD_PWM10_IS_GPIO
#define PAD_PWM10_IS_GPIO 0
#endif 

#define PAD_PWM11 9999
#ifndef PAD_PWM11_IS_GPIO
#define PAD_PWM11_IS_GPIO 0
#endif 

#define PAD_GPIO26 9999
#ifndef PAD_GPIO26_IS_GPIO
#define PAD_GPIO26_IS_GPIO 0
#endif 

#define PAD_GPIO27 9999
#ifndef PAD_GPIO27_IS_GPIO
#define PAD_GPIO27_IS_GPIO 0
#endif 

#define BALL_B16 PAD_I2S_OUT_BCK
#define PAD_I2S_OUT_BCK 89
#define GPIO_PAD_89 GPIO88
#ifndef BALL_B16_IS_GPIO
#define BALL_B16_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_BCK_IS_GPIO
#define PAD_I2S_OUT_BCK_IS_GPIO BALL_B16_IS_GPIO
#endif 

#define BALL_A18 PAD_DDCR_CK
#define PAD_DDCR_CK 53
#define GPIO_PAD_53 GPIO52
#ifndef BALL_A18_IS_GPIO
#define BALL_A18_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_CK_IS_GPIO
#define PAD_DDCR_CK_IS_GPIO BALL_A18_IS_GPIO
#endif 

#define BALL_B18 PAD_DDCR_DA
#define PAD_DDCR_DA 52
#define GPIO_PAD_52 GPIO51
#ifndef BALL_B18_IS_GPIO
#define BALL_B18_IS_GPIO 0
#endif 
#ifndef PAD_DDCR_DA_IS_GPIO
#define PAD_DDCR_DA_IS_GPIO BALL_B18_IS_GPIO
#endif 

#define BALL_A15 PAD_PWM0
#define PAD_PWM0 146
#define GPIO_PAD_146 GPIO145
#ifndef BALL_A15_IS_GPIO
#define BALL_A15_IS_GPIO 0
#endif 
#ifndef PAD_PWM0_IS_GPIO
#define PAD_PWM0_IS_GPIO BALL_A15_IS_GPIO
#endif 

#define BALL_B15 PAD_PWM1
#define PAD_PWM1 147
#define GPIO_PAD_147 GPIO146
#ifndef BALL_B15_IS_GPIO
#define BALL_B15_IS_GPIO 0
#endif 
#ifndef PAD_PWM1_IS_GPIO
#define PAD_PWM1_IS_GPIO BALL_B15_IS_GPIO
#endif 

#define BALL_A17 PAD_PWM2
#define PAD_PWM2 148
#define GPIO_PAD_148 GPIO147
#ifndef BALL_A17_IS_GPIO
#define BALL_A17_IS_GPIO 0
#endif 
#ifndef PAD_PWM2_IS_GPIO
#define PAD_PWM2_IS_GPIO BALL_A17_IS_GPIO
#endif 

#define BALL_H15 PAD_PWM3
#define PAD_PWM3 149
#define GPIO_PAD_149 GPIO148
#ifndef BALL_H15_IS_GPIO
#define BALL_H15_IS_GPIO 0
#endif 
#ifndef PAD_PWM3_IS_GPIO
#define PAD_PWM3_IS_GPIO BALL_H15_IS_GPIO
#endif 

#define PAD_PWM4 9999
#ifndef PAD_PWM4_IS_GPIO
#define PAD_PWM4_IS_GPIO 0
#endif 

#define PAD_PWM5 9999
#ifndef PAD_PWM5_IS_GPIO
#define PAD_PWM5_IS_GPIO 0
#endif 

#define PAD_PWM6 9999
#ifndef PAD_PWM6_IS_GPIO
#define PAD_PWM6_IS_GPIO 0
#endif 

#define PAD_PWM12 9999
#ifndef PAD_PWM12_IS_GPIO
#define PAD_PWM12_IS_GPIO 0
#endif 

#define PAD_PWM7 9999
#ifndef PAD_PWM7_IS_GPIO
#define PAD_PWM7_IS_GPIO 0
#endif 

#define BALL_E12 PAD_GPIO7
#define PAD_GPIO7 61
#define GPIO_PAD_61 GPIO60
#ifndef BALL_E12_IS_GPIO
#define BALL_E12_IS_GPIO 0
#endif 
#ifndef PAD_GPIO7_IS_GPIO
#define PAD_GPIO7_IS_GPIO BALL_E12_IS_GPIO
#endif 

#define BALL_B17 PAD_SPDIF_OUT
#define PAD_SPDIF_OUT 86
#define GPIO_PAD_86 GPIO85
#ifndef BALL_B17_IS_GPIO
#define BALL_B17_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_OUT_IS_GPIO
#define PAD_SPDIF_OUT_IS_GPIO BALL_B17_IS_GPIO
#endif 

#define PAD_GPIO23 9999
#ifndef PAD_GPIO23_IS_GPIO
#define PAD_GPIO23_IS_GPIO 0
#endif 

#define BALL_C16 PAD_I2S_OUT_MCK
#define PAD_I2S_OUT_MCK 88
#define GPIO_PAD_88 GPIO87
#ifndef BALL_C16_IS_GPIO
#define BALL_C16_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_MCK_IS_GPIO
#define PAD_I2S_OUT_MCK_IS_GPIO BALL_C16_IS_GPIO
#endif 

#define PAD_GPIO24 9999
#ifndef PAD_GPIO24_IS_GPIO
#define PAD_GPIO24_IS_GPIO 0
#endif 

#define BALL_C15 PAD_I2S_OUT_WS
#define PAD_I2S_OUT_WS 87
#define GPIO_PAD_87 GPIO86
#ifndef BALL_C15_IS_GPIO
#define BALL_C15_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_WS_IS_GPIO
#define PAD_I2S_OUT_WS_IS_GPIO BALL_C15_IS_GPIO
#endif 

#define BALL_E15 PAD_SPDIF_IN
#define PAD_SPDIF_IN 85
#define GPIO_PAD_85 GPIO84
#ifndef BALL_E15_IS_GPIO
#define BALL_E15_IS_GPIO 0
#endif 
#ifndef PAD_SPDIF_IN_IS_GPIO
#define PAD_SPDIF_IN_IS_GPIO BALL_E15_IS_GPIO
#endif 

#define PAD_GPIO13 9999
#ifndef PAD_GPIO13_IS_GPIO
#define PAD_GPIO13_IS_GPIO 0
#endif 

#define BALL_C17 PAD_I2S_OUT_SD
#define PAD_I2S_OUT_SD 90
#define GPIO_PAD_90 GPIO89
#ifndef BALL_C17_IS_GPIO
#define BALL_C17_IS_GPIO 0
#endif 
#ifndef PAD_I2S_OUT_SD_IS_GPIO
#define PAD_I2S_OUT_SD_IS_GPIO BALL_C17_IS_GPIO
#endif 

#define PAD_GPIO14 9999
#ifndef PAD_GPIO14_IS_GPIO
#define PAD_GPIO14_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD1 9999
#ifndef PAD_I2S_OUT_SD1_IS_GPIO
#define PAD_I2S_OUT_SD1_IS_GPIO 0
#endif 

#define PAD_GPIO15 9999
#ifndef PAD_GPIO15_IS_GPIO
#define PAD_GPIO15_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD2 9999
#ifndef PAD_I2S_OUT_SD2_IS_GPIO
#define PAD_I2S_OUT_SD2_IS_GPIO 0
#endif 

#define PAD_GPIO16 9999
#ifndef PAD_GPIO16_IS_GPIO
#define PAD_GPIO16_IS_GPIO 0
#endif 

#define PAD_I2S_OUT_SD3 9999
#ifndef PAD_I2S_OUT_SD3_IS_GPIO
#define PAD_I2S_OUT_SD3_IS_GPIO 0
#endif 

#define BALL_C18 PAD_GPIO17
#define PAD_GPIO17 71
#define GPIO_PAD_71 GPIO70
#ifndef BALL_C18_IS_GPIO
#define BALL_C18_IS_GPIO 0
#endif 
#ifndef PAD_GPIO17_IS_GPIO
#define PAD_GPIO17_IS_GPIO BALL_C18_IS_GPIO
#endif 

#define BALL_D14 PAD_I2S_IN_WS
#define PAD_I2S_IN_WS 82
#define GPIO_PAD_82 GPIO81
#ifndef BALL_D14_IS_GPIO
#define BALL_D14_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_WS_IS_GPIO
#define PAD_I2S_IN_WS_IS_GPIO BALL_D14_IS_GPIO
#endif 

#define BALL_F15 PAD_I2S_IN_BCK
#define PAD_I2S_IN_BCK 83
#define GPIO_PAD_83 GPIO82
#ifndef BALL_F15_IS_GPIO
#define BALL_F15_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_BCK_IS_GPIO
#define PAD_I2S_IN_BCK_IS_GPIO BALL_F15_IS_GPIO
#endif 

#define BALL_E14 PAD_I2S_IN_SD
#define PAD_I2S_IN_SD 84
#define GPIO_PAD_84 GPIO83
#ifndef BALL_E14_IS_GPIO
#define BALL_E14_IS_GPIO 0
#endif 
#ifndef PAD_I2S_IN_SD_IS_GPIO
#define PAD_I2S_IN_SD_IS_GPIO BALL_E14_IS_GPIO
#endif 

#define PAD_GPIO0 9999
#ifndef PAD_GPIO0_IS_GPIO
#define PAD_GPIO0_IS_GPIO 0
#endif 

#define PAD_GPIO1 9999
#ifndef PAD_GPIO1_IS_GPIO
#define PAD_GPIO1_IS_GPIO 0
#endif 

#define PAD_GPIO2 9999
#ifndef PAD_GPIO2_IS_GPIO
#define PAD_GPIO2_IS_GPIO 0
#endif 

#define PAD_GPIO3 9999
#ifndef PAD_GPIO3_IS_GPIO
#define PAD_GPIO3_IS_GPIO 0
#endif 

#define PAD_GPIO4 9999
#ifndef PAD_GPIO4_IS_GPIO
#define PAD_GPIO4_IS_GPIO 0
#endif 

#define PAD_GPIO5 9999
#ifndef PAD_GPIO5_IS_GPIO
#define PAD_GPIO5_IS_GPIO 0
#endif 

#define PAD_GPIO6 9999
#ifndef PAD_GPIO6_IS_GPIO
#define PAD_GPIO6_IS_GPIO 0
#endif 

#define BALL_F12 PAD_GPIO8
#define PAD_GPIO8 62
#define GPIO_PAD_62 GPIO61
#ifndef BALL_F12_IS_GPIO
#define BALL_F12_IS_GPIO 0
#endif 
#ifndef PAD_GPIO8_IS_GPIO
#define PAD_GPIO8_IS_GPIO BALL_F12_IS_GPIO
#endif 

#define BALL_E11 PAD_GPIO9
#define PAD_GPIO9 63
#define GPIO_PAD_63 GPIO62
#ifndef BALL_E11_IS_GPIO
#define BALL_E11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO9_IS_GPIO
#define PAD_GPIO9_IS_GPIO BALL_E11_IS_GPIO
#endif 

#define BALL_F11 PAD_GPIO10
#define PAD_GPIO10 64
#define GPIO_PAD_64 GPIO63
#ifndef BALL_F11_IS_GPIO
#define BALL_F11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO10_IS_GPIO
#define PAD_GPIO10_IS_GPIO BALL_F11_IS_GPIO
#endif 

#define BALL_B11 PAD_GPIO11
#define PAD_GPIO11 65
#define GPIO_PAD_65 GPIO64
#ifndef BALL_B11_IS_GPIO
#define BALL_B11_IS_GPIO 0
#endif 
#ifndef PAD_GPIO11_IS_GPIO
#define PAD_GPIO11_IS_GPIO BALL_B11_IS_GPIO
#endif 

#define BALL_B12 PAD_GPIO12
#define PAD_GPIO12 66
#define GPIO_PAD_66 GPIO65
#ifndef BALL_B12_IS_GPIO
#define BALL_B12_IS_GPIO 0
#endif 
#ifndef PAD_GPIO12_IS_GPIO
#define PAD_GPIO12_IS_GPIO BALL_B12_IS_GPIO
#endif 

#define BALL_C11 PAD_SAR_GPIO0
#define PAD_SAR_GPIO0 42
#define GPIO_PAD_42 GPIO41
#ifndef BALL_C11_IS_GPIO
#define BALL_C11_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO0_IS_GPIO
#define PAD_SAR_GPIO0_IS_GPIO BALL_C11_IS_GPIO
#endif 

#define BALL_B10 PAD_SAR_GPIO1
#define PAD_SAR_GPIO1 43
#define GPIO_PAD_43 GPIO42
#ifndef BALL_B10_IS_GPIO
#define BALL_B10_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO1_IS_GPIO
#define PAD_SAR_GPIO1_IS_GPIO BALL_B10_IS_GPIO
#endif 

#define BALL_E10 PAD_SAR_GPIO2
#define PAD_SAR_GPIO2 44
#define GPIO_PAD_44 GPIO43
#ifndef BALL_E10_IS_GPIO
#define BALL_E10_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO2_IS_GPIO
#define PAD_SAR_GPIO2_IS_GPIO BALL_E10_IS_GPIO
#endif 

#define BALL_F10 PAD_SAR_GPIO3
#define PAD_SAR_GPIO3 45
#define GPIO_PAD_45 GPIO44
#ifndef BALL_F10_IS_GPIO
#define BALL_F10_IS_GPIO 0
#endif 
#ifndef PAD_SAR_GPIO3_IS_GPIO
#define PAD_SAR_GPIO3_IS_GPIO BALL_F10_IS_GPIO
#endif 

#define PAD_SAR_GPIO4 9999
#ifndef PAD_SAR_GPIO4_IS_GPIO
#define PAD_SAR_GPIO4_IS_GPIO 0
#endif 

#define BALL_A12 PAD_VID1
#define PAD_VID1 50
#define GPIO_PAD_50 GPIO49
#ifndef BALL_A12_IS_GPIO
#define BALL_A12_IS_GPIO 0
#endif 
#ifndef PAD_VID1_IS_GPIO
#define PAD_VID1_IS_GPIO BALL_A12_IS_GPIO
#endif 

#define BALL_C12 PAD_VID0
#define PAD_VID0 49
#define GPIO_PAD_49 GPIO48
#ifndef BALL_C12_IS_GPIO
#define BALL_C12_IS_GPIO 0
#endif 
#ifndef PAD_VID0_IS_GPIO
#define PAD_VID0_IS_GPIO BALL_C12_IS_GPIO
#endif 

#define BALL_C10 PAD_LED1
#define PAD_LED1 48
#define GPIO_PAD_48 GPIO47
#ifndef BALL_C10_IS_GPIO
#define BALL_C10_IS_GPIO 0
#endif 
#ifndef PAD_LED1_IS_GPIO
#define PAD_LED1_IS_GPIO BALL_C10_IS_GPIO
#endif 

#define BALL_A10 PAD_LED0
#define PAD_LED0 47
#define GPIO_PAD_47 GPIO46
#ifndef BALL_A10_IS_GPIO
#define BALL_A10_IS_GPIO 0
#endif 
#ifndef PAD_LED0_IS_GPIO
#define PAD_LED0_IS_GPIO BALL_A10_IS_GPIO
#endif 

#define PAD_WOL_INT 9999
#ifndef PAD_WOL_INT_IS_GPIO
#define PAD_WOL_INT_IS_GPIO 0
#endif 

#define BALL_A9 PAD_GPIO_PM9
#define PAD_GPIO_PM9 18
#define GPIO_PAD_18 GPIO17
#ifndef BALL_A9_IS_GPIO
#define BALL_A9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM9_IS_GPIO
#define PAD_GPIO_PM9_IS_GPIO BALL_A9_IS_GPIO
#endif 

#define BALL_C9 PAD_GPIO_PM8
#define PAD_GPIO_PM8 17
#define GPIO_PAD_17 GPIO16
#ifndef BALL_C9_IS_GPIO
#define BALL_C9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM8_IS_GPIO
#define PAD_GPIO_PM8_IS_GPIO BALL_C9_IS_GPIO
#endif 

#define PAD_GPIO_PM7 9999
#ifndef PAD_GPIO_PM7_IS_GPIO
#define PAD_GPIO_PM7_IS_GPIO 0
#endif 

#define BALL_B7 PAD_GPIO_PM6
#define PAD_GPIO_PM6 15
#define GPIO_PAD_15 GPIO14
#ifndef BALL_B7_IS_GPIO
#define BALL_B7_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM6_IS_GPIO
#define PAD_GPIO_PM6_IS_GPIO BALL_B7_IS_GPIO
#endif 

#define BALL_D9 PAD_GPIO_PM5
#define PAD_GPIO_PM5 14
#define GPIO_PAD_14 GPIO13
#ifndef BALL_D9_IS_GPIO
#define BALL_D9_IS_GPIO 0
#endif 
#ifndef PAD_GPIO_PM5_IS_GPIO
#define PAD_GPIO_PM5_IS_GPIO BALL_D9_IS_GPIO
#endif 


// PADS group name to index
#define PADS_PCMCONFIG_MODE1        1223
#define PADS_PCMCONFIG_MODE2        1224
#define PADS_PCMCONFIG1_MODE1       1225
#define PADS_PCMCONFIG1_MODE2       1226
#define PADS_PCMCONFIG1_MODE3       1227
#define PADS_PCM2CONFIG_MODE1       1228
#define PADS_PCM2CONFIG_MODE2       1229
#define PADS_PCM2CONFIG_MODE3       1230
#define PADS_PCM2CONFIG1_MODE1      1231
#define PADS_PCM2CONFIG1_MODE2      1232
#define PADS_ET_MODE1               1233
#define PADS_ET_MODE2               1234
#define PADS_DDCR                   1235
#define PADS_DDCR2                  1236
#define PADS_PCM                    1237

// chip capbilities
#define CHIP_HAS_BT656_IN           0
#define CHIP_HAS_TS0                1
#define CHIP_HAS_TS1                0 
#define CHIP_HAS_LVDS_10BIT_X2      1
#define CHIP_HAS_LVDS_8BIT_X2       1
#define CHIP_HAS_LVDS_8BIT_X1       1
#define CHIP_HAS_CIMAX              0
#define CHIP_HAS_USB_P0             1
#define CHIP_HAS_USB_P1             1
#define CHIP_HAS_USBVBUS0           0
#define CHIP_HAS_USBVBUS1           0
#define CHIP_HAS_UART1_MODE1        1 
#define CHIP_HAS_UART1_MODE2        1
#define CHIP_HAS_UART1_MODE3        1 
#define CHIP_HAS_PCMCIA1            0
#define CHIP_HAS_PCMCIA2            0
#define CHIP_HAS_PCMCIA             0
#define CHIP_HAS_UART2_MODE1        1 
#define CHIP_HAS_UART2_MODE2        1 
#define CHIP_HAS_UART2_MODE3        1 
#define CHIP_HAS_RGB_A              1 
#define CHIP_HAS_RGB_B              1 
#define CHIP_HAS_RGB_C              1 
#define CHIP_HAS_HDMI_A             1 
#define CHIP_HAS_HDMI_B             1 
#define CHIP_HAS_HDMI_C             1 
#define CHIP_HAS_SPI_CZ1            1 
#define CHIP_HAS_SPI_CZ2            0 
#define CHIP_HAS_SPI_CZ3            0
#define CHIP_HAS_DDCR               1 
#define CHIP_HAS_DDCR2              1 
#define CHIP_HAS_TCON               1
#define CHIP_HAS_ET_MODE0_MII       1 
#define CHIP_HAS_ET_MODE0_RMII      1 
#define CHIP_HAS_ET_MODE1_MII       1 
#define CHIP_HAS_ET_MODE1_RMII      1 
#define CHIP_HAS_ET_MODE2_MII       1
#define CHIP_HAS_ET_MODE2_RMII      1
#define CHIP_HAS_I2S_IN             0 
#define CHIP_HAS_I2S_OUT            0
#define CHIP_HAS_SPDIF_IN           0 
#define CHIP_HAS_SPDIF_OUT          0
#define CHIP_HAS_DDR_A_CMD          1
#define CHIP_HAS_DDR_A_DATA         1
#define CHIP_HAS_DDR_B_CMD          1
#define CHIP_HAS_DDR_B_DATA         1
#define CHIP_USE_PCM_CDN_IN_PCM2    0
#define CHIP_USE_I2S_IN_IN_PCM      0
#define CHIP_USE_I2S_OUT_IN_PCM     0
#define CHIP_USE_SPDIF_IN_IN_PCM    0
#define CHIP_USE_SPDIF_OUT_IN_PCM   0
#define CHIP_USE_IIC_IN_DDCR2       0
#define CHIP_USE_PWM2_IN_GPIO14     0
#define CHIP_USE_PWM3_IN_GPIO15     0

// chip additional information
#define CHIP_FAMILY_TYPE            CHIP_FAMILY_EIFFEL

#endif /* _MSD8362MX_H_*/
