/*
 *#############################################################################
 *
 * Copyright (c) 2006-2014 MStar Semiconductor, Inc.
 * All rights reserved.
 *
 * Unless otherwise stipulated in writing, any and all information contained
 * herein regardless in any format shall remain the sole proprietary of
 * MStar Semiconductor Inc. and be kept in strict confidence
 * (¡§MStar Confidential Information¡¨) by the recipient.
 * Any unauthorized act including without limitation unauthorized disclosure,
 * copying, use, reproduction, sale, distribution, modification, disassembling,
 * reverse engineering and compiling of the contents of MStar Confidential
 * Information is unlawful and strictly prohibited. MStar hereby reserves the
 * rights to any and all damages, losses, costs and expenses resulting therefrom.
 *
 *#############################################################################
 */

#ifndef _MSTAR_ADDR_INC_
#define _MSTAR_ADDR_INC_

MS_BUS_MIU1_0768M                       = 0xD0000000
MS_BUS_MIU1_0512M                       = 0xC0000000
MS_BUS_MIU1_0256M                       = 0xB0000000
MS_BUS_MIU1_0000M                       = 0xA0000000
MS_BUS_MIU0_1792M                       = 0x90000000
MS_BUS_MIU0_1536M                       = 0x80000000
MS_BUS_MIU0_1280M                       = 0x70000000
MS_BUS_MIU0_1024M                       = 0x60000000
MS_BUS_MIU0_0768M                       = 0x50000000
MS_BUS_MIU0_0512M                       = 0x40000000
MS_BUS_MIU0_0256M                       = 0x30000000
MS_BUS_MIU0_0000M                       = 0x20000000
MS_BUS_RIU_ADDR                         = 0x1F000000
MS_BUS_XIU_SPI_ADDR                     = 0x14000000
MS_BUS_BOOT_ADDR                        = 0x00000000

#endif
