CFLAGS += -I$(srctree)/inc/munich/board -I$(srctree)/src -I$(srctree)/src/munich/include
AFLAGS += -I$(srctree)/inc/munich/board -I$(srctree)/src -I$(srctree)/src/munich/include

extra-y += sboot.lds
lib-y += boot.o 
lib-y += bootram.o
lib-y += bootrom.o 
lib-y += bootrom_pll.o
lib-y += bootrom_data_pll.o
lib-y += bootrom_clock.o 

lib-y += bootrom_miu.o
lib-y += bootrom_miu_str.o 
lib-y += bootrom_data_miu.o
lib-y += bootrom_data_str.o
lib-y += bootrom_peripheral.o
lib-y += bootrom_miu_txdqs.o
lib-y += bootrom_miu_deskew.o

lib-y += bootrom_cache.o 
lib-y += drvPadConf.o

lib-y += apiBDMA.o 
lib-y += arm_compile.o

